### ISSUE TITLE
VictoryBrushContainer should not show "rezise-cursor" when allowResize is false

### ISSUE THREAD

**Issue by johnhydroware** [FormidableLabs/victory#1095] opened 2018-08-20 08:37 UTC
### The Problem

When "VictoryBrushContainer" and setting "allowResize" to "false" the cursor still changes to a double-arrow-cursor in the edges of the brush. It should only show the "hand" since moving the brush is the only available action for the user.

**Comment by boygirl** [comment] 2018-08-21 18:03
Good catch, thank you!

**Comment by erick2014** [comment] 2018-09-15 18:29
Hello, I want to try to solve this

**Comment by boygirl** [comment] 2018-09-15 19:03
@erick2014 thanks! Please let me know if you have any questions about how to get started :)

**Comment by erick2014** [comment] 2018-09-15 23:01
hey @boygirl is there any way to reproduce this issue? I'm new in this and I have no idea what is the VictoryBrushContainer

**Comment by narinluangrath** [comment] 2018-09-17 18:20
Hi @erick2014, here's a demo of the `VictoryBrushContainer`: https://formidable.com/open-source/victory/docs/victory-brush-container/

The BrushContainer adds a highlighted region to the chart on the bottom. The `allowResize` prop controls whether or not it can be resized. Ideally, when the user hovers over the edge of the highlighted region and `allowResize` is set to false, the cursor shouldn't switch to the "resize" symbol since the user isn't allow to resize it.

**Comment by erick2014** [comment] 2018-09-18 00:43
owww, thankyou so much @narinluangrath

**Comment by erick2014** [comment] 2018-09-22 20:38
@johnhydroware would be helpfull if you u share the code u are using and some pictures

**Comment by erick2014** [comment] 2018-09-23 17:35
@boygirl https://github.com/FormidableLabs/victory/pull/1124/files

**Comment by erick2014** [comment] 2018-09-26 23:15
@boygirl you can close this issue now

**Closed** 2018-09-27 00:53 UTC
Labels: beginner-friendly, bug
