### ISSUE TITLE
victory-bar plotting issue

### ISSUE THREAD

**Issue by stephenotalora** [FormidableLabs/victory#171] opened 2016-01-15 17:39 UTC
are stacked bars suppose to look like the image bellow for more that one data point? or am I passing data incorrectly? do note that the picture is from: http://victory.formidable.com/docs/victory-bar
<img width="1112" alt="screen shot 2016-01-14 at 9 31 42 pm" src="https://cloud.githubusercontent.com/assets/6519974/12346137/8c7b6e5e-bb06-11e5-9e45-61a079d00419.png">

The data looks as follows: 
```javascript
var data = {[
    [
      {x: 1, y: 1},
      {x: 2, y: 2},
      {x: 3, y: 3}
    ],
    [
      {x: 1, y: 2},
      {x: 2, y: 1},
      {x: 3, y: 1}
    ],
    [
      {x: 1, y: 3},
      {x: 2, y: 4},
      {x: 3, y: 2}
    ],
    [
      {x: 4, y: 1},
      {x: 5, y: 2},
      {x: 6, y: 3}
    ],
    [
      {x: 4, y: 2},
      {x: 5, y: 1},
      {x: 6, y: 1}
    ],
    [
      {x: 4, y: 3},
      {x: 5, y: 4},
      {x: 6, y: 2}
    ],
  ]};
```

essentially I want to accomplish something like this: 
<img src="http://betterevaluation.org/sites/default/files/2d_StackedColumnChart2.png">

The plotting looks really odd unless I'm missing something? it actually looks the same as the first image when I instantiate VictoryBar in my React component.

**Comment by dandelany** [comment] 2016-01-15 17:59
@stephenotalora This does seem like a bug that should be fixed - however, a workaround is to combine the data series you mention above to ensure that in each series, there is a Y-value for all X-values. eg.:

```
var data = [
    [
      {x: 1, y: 1},
      {x: 2, y: 2},
      {x: 3, y: 3},
      {x: 4, y: 1},
      {x: 5, y: 2},
      {x: 6, y: 3}
    ],
    [
      {x: 1, y: 2},
      {x: 2, y: 1},
      {x: 3, y: 1},
      {x: 4, y: 2},
      {x: 5, y: 1},
      {x: 6, y: 1}
    ],
    [
      {x: 1, y: 3},
      {x: 2, y: 4},
      {x: 3, y: 2},
      {x: 4, y: 3},
      {x: 5, y: 4},
      {x: 6, y: 2}
    ],
  ]
```

...works as expected:

https://jsfiddle.net/dandelany/uazwgrm6/

**Comment by knowbody** [comment] 2016-01-15 18:34
looking at this issue there are a few more things that I found:
- https://jsbin.com/tudezagesa/edit?js,output (this should display 3 bars and have 3 bars stacked on top of each other) - displays 2 only
  - similar thing happens here - https://jsbin.com/cusulogupi/edit?js,output

- https://jsbin.com/vibekupugo/1/edit?js,output (this should display 3 groups of 3 bars in each group) - nothing displayed, even though the *y values* are 1, not 0

**Comment by exogen** [comment] 2016-01-15 18:41
@knowbody Definitely some weird layout going on. Here's one of the bars in the inspector on the second chart – only half of the red bar is visible, and goes halfway under the yellow bar (I think the yellow and blue bars are supposed to be rendered higher up):

<img width="199" alt="screen shot 2016-01-15 at 10 39 49 am" src="https://cloud.githubusercontent.com/assets/53522/12361681/6ca18e38-bb74-11e5-99a0-3cd2e0e65ec5.png">

**Comment by stephenotalora** [comment] 2016-01-15 19:52
thanks guys I'm trying to render 70 data entries at the the time and with more than two it can get pretty whacky, essentially I get little blocks across the entire area of the chart. I will try to provide a picture shortly.

**Comment by knowbody** [comment] 2016-01-15 20:00
closing this issue here, as it's a duplicate of https://github.com/FormidableLabs/victory-bar/issues/83

let's continue there, as it's related to the victory-bar

**Closed by knowbody** 2016-01-15 20:00 UTC
Labels: bug

**Comment by boygirl** [comment] 2016-01-15 20:02
thanks @knowbody do you mind duplicating your other findings in separate bug issues on victory-bar?

**Comment by knowbody** [comment] 2016-01-15 20:03
@boygirl yup, :+1:
