### ISSUE TITLE
VictoryAxis tickFormat values undefined after upgrading to 0.22.2

### ISSUE THREAD

**Issue by Kebie** [FormidableLabs/victory#761] opened 2017-09-25 17:41 UTC
I have a horizontal custom chart that worked fine, then I upgraded to 0.22.2 and all my custom tick format's are undefined now.

`<VictoryAxis
        tickValues={[0, 25, 50, 75, 100]}
        tickCount={5}
        tickFormat={(t) => `${t}%`}
        style={tickStyle}
        orientation={'top'}
        domain={[0, 100]}
        domainPadding={0}
 />`

I saw you added something to have additional arguments? however if I even dump "t" to console everything is undefined now. The documentation example at https://formidable.com/open-source/victory/docs/victory-axis/ no longer works for me either when I copy and paste it in.

**Comment by boygirl** [comment] 2017-09-25 19:32
@Kebie I'm not able to reproduce this issue. I created a jsfiddle based on the code you provided above, and it works. Can you alter the fiddle until you can reproduce the failure you're seeing?

https://jsfiddle.net/boygirl/r3kk5v37/

**Comment by boygirl** [comment] 2017-09-26 18:28
@Kebie I'm going to close this issue for now, but I'll be happy to re-open it if you can provide more info for a reproduction.

**Closed by boygirl** 2017-09-26 18:28 UTC

**Comment by Kebie** [comment] 2017-10-24 18:15
Thank you for helping and sorry I haven't gotten back earlier.

Is there a difference in what you have in Victory.min.js latest in your JSFiddle? I forked it and added a bit more without any styling or formatting. https://jsfiddle.net/p17wcnt3/ , yes it does work.

I upgraded to version 0.24.0 on my project, made sure to re-pack and still the same error.
<img width="566" alt="screen shot 2017-10-24 at 11 09 17 am" src="https://user-images.githubusercontent.com/1324411/31960365-69b1cf08-b8ac-11e7-81a9-dab5f0c3f208.png">
![screen shot 2017-10-24 at 11 08 59 am](https://user-images.githubusercontent.com/1324411/31960371-6dab431e-b8ac-11e7-948b-17666600e224.png)

I have gone step by step of rebuilding my graph from scratch and it breaks down when setting the y and x values for the bar graph. Are the set tickValues not overwriting properly?

**Comment by boygirl** [comment] 2017-10-25 02:43
@Kebie thanks for more detail. I made a more thorough reproduction of your issue in a fiddle: https://jsfiddle.net/boygirl/p17wcnt3/3/

I'm still not seeing the issue you're seeing either there or locally. I'll keep digging, though

**Comment by Kebie** [comment] 2017-10-25 17:24
I just went through a fun hour of deleting my node_modules, upgrading my version of NPM hitting new errors with other unrelated packages, not being able to run my startup scripts, webpack errors, npm ERR! code ELIFECYCLE errors! and finally cloning an old version of project and copying over all my components and containers, doing a new npm install, new npm save of victory, and VIOLA I can get % signs on the end of ticks and not have undefined variable error.

Thank you for all your help! This is the javascript eco system we live and love! I have no idea what the error was, I feel it was something unrelated to victory itself. Thank you for all your hard work on this project however.

**Comment by blb451** [comment] 2018-04-13 17:50
Just ran into this issue with 22.2 as well, updated to 25.7 after reading this and the issue vanished 👍
