### ISSUE TITLE
Unexected axis label behaviour when orientation is set with a const value

### ISSUE THREAD

**Issue by StraightOuttaCrompton** [FormidableLabs/victory#1454] opened 2019-12-04 11:18 UTC
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When orientation is set like so
```js
const orientation = type === "positive" ? "right" : "left";
```
where ```type``` is either ```"positive"``` or ```"negative"```, the following is rendered.

![orientation={orientation}](https://user-images.githubusercontent.com/16123253/70137624-43f85b80-1686-11ea-805a-cadbcf356b6f.png)

This is unexpected behaviour as ```orientation``` has the values of either ```"right"``` or ```"left"```, and so should render the same as the expected behaviour below.

***Expected behaviour***

When ```orientation = "left"```

![orientation={ left }](https://user-images.githubusercontent.com/16123253/70137732-8752ca00-1686-11ea-80c3-b43ac768101f.png)

When ```orientation = "right"```

![orientation={ right }](https://user-images.githubusercontent.com/16123253/70137718-80c45280-1686-11ea-99fd-fceeb0fe3035.png)

### Reproduction

Clone the [repository](https://github.com/StraightOuttaCrompton/victory-bar-chart-label-orientation), and start by running the command ```npm install && npm start```. 

The unexpected behaviour is demonstrated in the file ```ExampleBarChart```, lines 58 and 79.

***To reproduce expected behaviour***
* Uncomment the line 80 and comment the lines 79 and 81 to reproduce ```orientation = "left"``` behaviour.
* Uncomment the line 81 and comment the lines 79 and 80 to reproduce ```orientation = "right"``` behaviour.

**Comment by StraightOuttaCrompton** [comment] 2019-12-04 11:21
I would like to apologies for the frequency of my recent issue submissions - I am currently using the library alot for a project I am working on and so keep discovering little quirks. 

I really appreciate all the hard work you are doing!

**Comment by boygirl** [comment] 2019-12-12 20:24
@StraightOuttaCrompton no worries at all! Apologies for the delay in getting back to you. Here's what's going on with your issue:

1) `VictoryChart` is looking at all its children and determining a domain and a shared stringMap for all of them to use
2) VictoryChart gives that domain to its children, and since you haven't set explicit `tickValues` on your axes, it's using that shared domain and stringMap to determine tickValues
3) you're rendering two vertical axes on your chart, one with orientation="right" and one with orientation="left". Both sets of expected behavior are happening at once. When I comment out the lines you suggest, both axes are still rendered, they are just rendered exactly on top of each other.

I'm going to close this issue, but let me know if there's another way to approach what you're trying to do that you have questions about. I think you might actually be looking for something like this: https://codesandbox.io/s/v6zzl6jl77

**Closed by boygirl** 2019-12-12 20:24 UTC

**Comment by StraightOuttaCrompton** [comment] 2019-12-17 18:35
Ah I see what is happening. 

I have tried using the approach you have linked, however I cannot figure out a complete solution for a horizontal chart. Here is as far as I could get - https://codesandbox.io/s/negative-aware-tick-label-6euqj

As you can see, the labels are not positioned correctly based on how long they are. Do you have any suggestions on how to proceed?

**Comment by boygirl** [comment] 2019-12-17 19:00
Try changing the `textAnchor`. I altered your example. There was also a bit of an issue with -0 and `Math.sign`

https://codesandbox.io/s/negative-aware-tick-label-ded45

**Comment by StraightOuttaCrompton** [comment] 2019-12-17 19:13
Ah brilliant, thank you very much!

I have just now managed to achieve the desired result by using the ```tickFormat``` property on ```VictoryAxis``` like so.

```js
tickFormat={(t: string) => {
    const labelInDataSet = parsedData
        .map(datum => datum.x)
        .includes(t);

        return labelInDataSet ? t : "";
}}
```
As seen in this branch - https://github.com/StraightOuttaCrompton/victory-bar-chart-label-orientation/tree/solution

Do you think it matters which solution I use?

**Comment by boygirl** [comment] 2019-12-17 19:19
I don't think it will matter greatly for charts without tons of data, but you might choose the negative aware tick label solution to cut down on complexity and number of elements you end up rendering. Also, if you were using numeric data rather than string data, the solution you provide above may not be what you want, because then, the ticks and data would not necessairly be identical.

**Comment by StraightOuttaCrompton** [comment] 2019-12-17 19:22
Yeah, that makes sense. Thank you!
