### ISSUE TITLE
Zoom/Pan Performance is Very Poor

### ISSUE THREAD

**Issue by mindjuice** [FormidableLabs/victory#726] opened 2017-08-23 17:55 UTC
I've created a fairly simple demo with just `VictoryLine` components with randomly generated data inside a `VictoryZoomContainer` (25 lines with 1000 points each).

When you zoom the container and when you pan around, the rendering is very slow (2-3 fps maybe).

I've tried other React graph libraries in SVG mode (like `react-stockcharts`), and they are much faster with the same number of lines and data points (and even faster if rendering in canvas mode).

Am I doing something wrong or is this a bug or just how it is?

Victory codesandbox: https://codesandbox.io/s/my89v6j16j
React Stockcharts codesandbox: https://codesandbox.io/s/m37wxr387p

**Comment by mindjuice** [comment] 2017-09-07 13:36
@boygirl Is it possible to get a brief comment on this?  I'm wondering if you already know the cause of this, and if so, is it going to be fixed at some point soon?  Anything I can do to help with a fix?

I'm about to build up a pretty large set of visualization components and like the modularity of Victory, but without better performance, I'll have to use something else (`react-stockcharts` or maybe just `d3`).

Thank you.

**Comment by andreas-ateles** [comment] 2020-12-13 16:56
Victory seems nice, but I'm I'm trying to figure out the performance with a lot of data.

@boygirl Is there any canvas support in Victory? (SVG seems to be too slow in our case.) I assume no, as I haven't been able to find anything about that.

**Comment by becca-bailey** [comment] 2022-02-15 01:09
@andreas-ateles We do now have some experimental canvas support in Victory! https://formidable.com/blog/2021/data-viz-2/

**Comment by becca-bailey** [comment] 2022-02-15 01:10
This appears to be a duplicate of #655.

**Closed by becca-bailey** 2022-02-15 01:10 UTC
Labels: performance :chart_with_upwards_trend:
