### ISSUE TITLE
Missing labels in VictoryLine chart

### ISSUE THREAD

**Issue by thinkian** [FormidableLabs/victory#885] opened 2017-12-29 18:00 UTC
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I cannot see labels in a `<VictoryLine />` chart. This is true both with and without a custom `labelComponent` prop. If I switch to a `<VictoryBar />` component, I can see the labels.

I did notice that the default `labelComponent` for `<VictoryLine />` is `<VictoryLabel renderInPortal/>` which is different from just `<VictoryLabel />`. Am I required to wrap the chart with `<VictoryContainer />` or add a `<VictoryPortal />` somewhere? The docs do not make this clear with the example code, which is clearly rendering labels above the line.

### Reproduction

Code taken directly by merging two examples from docs:
```
<VictoryChart theme={VictoryTheme.material}>
   <VictoryLine
      style={{
        data: { stroke: '#c43a31' },
        parent: { border: '1px solid #ccc' }
       }}
       data={[
          { x: 1, y: 2 },
          { x: 2, y: 3 },
          { x: 3, y: 5 },
          { x: 4, y: 4 },
           { x: 5, y: 7 }
        ]}
        labels={datum => datum.y}
    />
</VictoryChart>
```

**Comment by boygirl** [comment] 2018-01-01 19:19
@thinkian the issue is that `VictoryLine` uses a clipped group component for animations, so labels that are rendered can be clipped if they are not popped up into the portal component. Unless you are using a custom svg container + `standalone={false}` for your chart, that portal component should be provided, and everything should work as expected for default `labelComponents`. Custom `labelComponents` may be wrapped in `VictoryPortal` to make them render in the top level portal like `labelComponent={<VictoryPortal><MyCustomLabel/></VictoryPortal>}`. 

Other possible solutions:
- add some padding to your clipped group component like 
`groupComponent={<VictoryClipContainer clipPadding={{ top: 10, right: 10 ... }}/>}`
- If you aren't using entrance / exit animations, you can replace the groupComponent entirely like `groupComponent={<g/>}`

 I can't reproduce the issue you're seeing with the code you provide above, which makes me think that you may be using an older version of Victory. Other possibilities may be something going wrong with a custom label or custom container.

I'm going to close this issue for now, but I will re-open it if your problem persists and you can provide more information to help me reproduce it.

**Closed by boygirl** 2018-01-01 19:19 UTC

**Comment by thinkian** [comment] 2018-01-02 16:42
@boygirl Ah okay. The issue must have been resolved in a later version of Victory. I was using the package installed from [Victory Tutorial](https://github.com/FormidableLabs/victory-tutorial), which is a project that is linked from the Getting Started section in your documentation. Apparently it is using `v0.17` of `victory`.

**Comment by thinkian** [comment] 2018-01-02 16:44
@boygirl Ah okay. The issue must have been resolved in a later version of Victory. I was using the package installed from [Victory Tutorial](https://github.com/FormidableLabs/victory-tutorial), which is a project that is linked from the Getting Started section in your documentation. Apparently it is using `victory v0.17`.

It is working with the current version. Thank you.
