### ISSUE TITLE
VictoryGroup is not passing the theme prop to its container

### ISSUE THREAD

**Issue by GreenGremlin** [FormidableLabs/victory#540] opened 2017-03-23 18:32 UTC
It seems VictoryGroup is not passing the theme prop through to its container. I can verify, in React tools, that the VictoryVoronoiContainer is given the default theme. This then means that it's tooltips also receive the default theme.

``` jsx
<VictoryChart theme={customTheme}>
    <VictoryGroup containerComponent={<VictoryVoronoiContainer />}>
```

**Comment by boygirl** [comment] 2017-03-23 20:08
@GreenGremlin thanks for pointing this out.

**Comment by GreenGremlin** [comment] 2017-03-30 19:55
It looks like VictoryVoronoiContainer is also not passing theme to its label component.

If I don't override the labelComponent, the tooltip will not get the custom theme.

``` javascript
<VictoryVoronoiContainer
    labelComponent={<VictoryTooltip theme={customTheme} />}
```

**Comment by GreenGremlin** [comment] 2017-04-19 18:13
This issue is still not fixed

**Comment by GreenGremlin** [comment] 2017-04-19 18:18
Sorry, VictoryGroup is not passing theme to its containerComponent. I still have to do this.

``` javascript
<VictoryChart
    theme={myTheme}
>
    <VictoryGroup
        containerComponent={(
            <VictoryVoronoiContainer
                theme={myTheme}
```

**Comment by boygirl** [comment] 2017-04-20 21:48
@GreenGremlin sorry I closed this one prematurely. I'll re-open. In the meantime, does it work if you put your container component on `VictoryChart`? We've been seeing odd behavior when container are used as group components rather than top level svg

**Comment by GreenGremlin** [comment] 2017-04-20 22:02
Is this what you're asking? If so then yes, VictoryChart is passing it's theme to it's containerComponent. This will not work for me, I need to use a group.

``` javascript
<VictoryChart
    theme={myTheme}
    containerComponent={(
        <VictoryVoronoiContainer
            theme={myTheme}
```

**Comment by bellawoo** [comment] 2018-02-16 15:10
I originally reported this in the Gitter conversation, but am adding this here since I believe they're the same root cause. 

Both default grayscale and material themes have a tooltip style object that inherits from baseLabelStyles. However, when I make changes to this style object for my custom theme, nothing changes.
Changes to theme does not appear in Tooltip:
```
<VictoryChart
  theme={mytheme}
>
  <VictoryBar
    data={data} x={x} y={y} labelComponent={<VictoryTooltip />}
  />
</VictoryChart>
```
I'm not using a container within VictoryChart. The only thing I have nested within VictoryChart is VictoryBar with a VictoryTooltip labelComponent. The theme is not propagating in VictoryTooltip. When I explicitly pass the theme prop in VictoryTooltip, the custom theme is applied to the flyoutStyle object, but not the style object that controls the label within the tooltip.

Changes to flyoutStyle within tooltip in theme is applied, but not to the label within the tooltip:
```
<VictoryChart
  theme={mytheme}
>
  <VictoryBar
    data={data} x={x} y={y} labelComponent={<VictoryTooltip theme={mytheme} />}
  />
</VictoryChart>
```

**Comment by MarkHammond34** [comment] 2020-06-18 19:00
I am seeing the same issue that @bellawoo pointed out. @boygirl Would you be able to provide a workaround other than passing the custom theme to the <VictoryTooltip/> component?
Thanks!

**Closed** 2020-08-27 21:09 UTC
Labels: bug
