### ISSUE TITLE
VictoryScatter size function no longer includes active param

### ISSUE THREAD

**Issue by tkiethanom** [FormidableLabs/victory#816] opened 2017-10-30 23:51 UTC
After upgrading from 0.21 to 0.24 the VictoryScatter component does not include the active param for the size function like it used to. Was this removed intentionally? If so what is the work around to get this kind of functionality back?

```
<VictoryScatter
size={(d, active) => {
  console.log(active); // undefined

  return active ? 5 : 3;
}}               
/>
```

**Comment by boygirl** [comment] 2017-10-31 22:28
@tkiethanom this is a regression. I'll get it cleaned up for the next release.

**Comment by boygirl** [comment] 2017-11-01 20:28
@tkiethanom actually, I'm not able to reproduce this issue in the latest version. Note that `undefined` is the expected value for `active` if the prop has not explicitly been set. 

I think what might be going on is that the evaluation of functional props has been moved down to the level of the primitive component, so `Point` in this example. If you're writing your own `dataComponent` for VictoryScatter, you'll want to evaluate this prop within your component.

I'm going to close this issue, since I can't reproduce it, but please let me know if you have more questions, or if you can't get this working correctly.

**Closed by boygirl** 2017-11-01 20:28 UTC

**Comment by tkiethanom** [comment] 2017-11-03 18:11
@boygirl So this example https://formidable.com/open-source/victory/gallery/voronoi-tooltips-grouped doesn't work with the latest version right?

**Comment by JayFields** [comment] 2018-02-09 17:43
@tkiethanom I opened a related issue #926. I found that the scatter dots to receive the active prop but not when they are being moused over directly.

**Comment by tkiethanom** [comment] 2020-02-15 02:37
For anyone still wondering about this, the way to use `active` is now: 

```
<VictoryScatter
  size={({active}) => {
    return active ? 5 : 3;
  }}               
/>
```
