### ISSUE TITLE
VictoryStack regression with empty data sets

### ISSUE THREAD

**Issue by dtesta** [FormidableLabs/victory#1137] opened 2018-10-05 15:25 UTC
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When passing an empty data set to a child chart within a Stack, the chart "steals" data from the next chart. This "stealing" continues until the last child chart has no data and charts `{x: index, y: index}`. As a work around, passing in junk data, such as `[{ x: "a", y: null }]` in the below examples, prevents this issue.

This appears to be a regression in how VictoryStack handles data sets between 0.27.0 and 0.27.1 (and persisting to the current versions).

### Reproduction

Expected: https://codesandbox.io/s/lp6k1x27oq (using `"victory": "0.27.0"`)
[![Expected Result](https://dzwonsemrish7.cloudfront.net/items/311d302I2N3i1X0w3h1N/expected.png?v=7e172e4e)
](http://cl.ly/220531ca42bc)

Actual: https://codesandbox.io/s/ol7wrv2yvy (using `"victory": "30.5.0"`)
[![Actual Result](https://dzwonsemrish7.cloudfront.net/items/293d1q2b3z2M0Q0G311U/actual.png?v=5bf4450e)
](http://cl.ly/afc5c8afa787)

**Comment by boygirl** [comment] 2018-10-05 15:42
@dtesta thank you for the helpful reproduction. I'll take a look

**Comment by becca-bailey** [comment] 2022-02-15 01:42
Closing for now, since this is not reproducible in the most recent version.

**Closed by becca-bailey** 2022-02-15 01:42 UTC
