### ISSUE TITLE
victory-core npm start errors

### ISSUE THREAD

**Issue by dishui** [FormidableLabs/victory#593] opened 2017-05-17 19:52 UTC
when running npm start in victory-core, I get the following error: 
I tried with node 4.2.6 npm 3.10.10  or node 6.10.3 and npm 4.5.0

WARNING in ./~/enzyme/build/react-compat.js
Module not found: Error: Cannot resolve module 'react-test-renderer/shallow' in /Users/vn0ibsb/development/formidablelabs/victory-core/node_modules/enzyme/build
 @ ./~/enzyme/build/react-compat.js 134:33-71
webpack: Compiled with warnings.

**Comment by boygirl** [comment] 2017-05-19 16:19
Closing as a duplicate of https://github.com/FormidableLabs/victory/issues/594 since these repos share infrastructure with builder

**Closed by boygirl** 2017-05-19 16:19 UTC
