### ISSUE TITLE
Theme for Tooltips not Updating tooltips

### ISSUE THREAD

**Issue by captDaylight** [FormidableLabs/victory#1156] opened 2018-10-22 20:30 UTC
I have a fairly straight forward bar graph with a global theme that is generally working as expected except for tooltips. 

```js
  ...

  tooltip: {
    style: assign({}, centeredLabelStyles, {
      padding: 16,
      pointerEvents: "none",
      fill: "#00ff00"
    }),
    flyoutStyle: {
      stroke: "#00ff00",
      strokeWidth: 0,
      fill: "#00ff00",
      pointerEvents: "none"
    },
    cornerRadius: 0,
    pointerLength: 8,
    pointerWidth: 16
  }
}
```

I made a [codesandbox](https://codesandbox.io/s/2o646k338n) to demonstrate the issue. The expected outcome is that when you hover on one of the bars you'd see bright green tooltip.

<img width="191" alt="screen shot 2018-10-22 at 4 26 12 pm" src="https://user-images.githubusercontent.com/700617/47317312-3d8c5900-d617-11e8-89ed-e7520111a104.png">

If I then take from the theme and add the flyoutStyle theme and add it directly to the VictoryTooltip Component you'll see that it then works as expected:

<img width="168" alt="screen shot 2018-10-22 at 4 27 56 pm" src="https://user-images.githubusercontent.com/700617/47317399-75939c00-d617-11e8-8c24-fa09a395605a.png">

```jsx
        <VictoryBar
          labelComponent={
            <VictoryTooltip
            flyoutStyle={{
                stroke: "#00ff00",
                strokeWidth: 0,
                fill: "#00ff00",
                pointerEvents: "none"
              }}
            />
          }
          ...
        />
```

**Comment by boygirl** [comment] 2018-10-25 17:49
@captDaylight thanks for this issue and reproduction. I'll get it fixed

**Comment by ecnaidar** [comment] 2019-03-28 14:09
@boygirl 
Having the same issue
Theme gets lost somewhere before rendering of the `<VictoryTooltip />` and during evaluation of `getCalculatedValues` it defaults to greyscale.
https://github.com/FormidableLabs/victory/blob/1eb61fb20969254e559c3fde8c9a98f202a5ea6d/packages/victory-tooltip/src/victory-tooltip.js#L198

Interestingly enough theme seems to be passed through to tooltips created by voronoi container but not to the ones that are created by charts. Which may mean that it is connected to that issue. https://github.com/FormidableLabs/victory/issues/370

**Comment by zzeni** [comment] 2020-04-28 17:16
Same here too.

I've managed to workaround it with just passing the same theme object to the tooltip component:

```tsx
const theme = { /* ... */ }

const tooltipComponent = <VictoryTooltip theme={theme} /* ... */ />

<VictoryChart
   theme={theme}
  //...
>
  // ...
  <VictoryStack labelComponent={tooltipComponent}>
    // ...
  </VictoryStack>
</VictoryChart>
```

though it's very likely to not be able to use it in the libs future versions, having in mind that the `theme` prop might be be removed from the tooltip with this PR: https://github.com/FormidableLabs/victory/pull/1533

**Comment by boygirl** [comment] 2020-07-08 00:44
`victory@35.0.0` includes a fix for this issue. The `tooltip` theme is now correctly applied whenever tooltips are used

**Closed by boygirl** 2020-07-08 00:44 UTC
