### ISSUE TITLE
onEnd called forever

### ISSUE THREAD

**Issue by dmwyatt** [FormidableLabs/victory#1803] opened 2021-03-10 00:35 UTC
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm fairly sure I'm just not understanding animation's `onEnd`, but maybe there's a bug?

Why does `onEnd` get called forever?

I'm just trying to get notified when the animation is done...

### Reproduction

https://codesandbox.io/s/victory-on-end-forever-nq09z?file=/src/App.js

**Comment by dmwyatt** [comment] 2021-03-10 19:04
I haven't quite grokked how everything fits together, but it looks like maybe there should be a check [here](https://github.com/FormidableLabs/victory/blob/f2822553787e77a6a45e2c7145c36128959781bc/packages/victory-core/src/victory-animation/victory-animation.js#L153) to see if onEnd has been called already?  Though, I'm still not quite clear on where and when `traverseQueue` could be called.

**Comment by boygirl** [comment] 2021-03-18 18:54
Oh, interesting! Thank you for the minimal reproduction, that's super helpful. I'll take a look.

**Comment by dmwyatt** [comment] 2021-03-18 19:19
Of note, that if you change the animations duration there's a corresponding change of the rate that the number increments, so I guess that might tell you...something?

**Comment by boygirl** [comment] 2021-03-22 20:58
Hmm... It also looks like `onEnd` is only getting called repeatedly if it includes a something that sets state. In your example, the whole tree that contains the chart is being rerendered after your `onEnd` sets the count state.

**Comment by becca-bailey** [comment] 2022-02-16 00:00
Closing this issue in favor of #2104

**Closed by becca-bailey** 2022-02-16 00:00 UTC
