### ISSUE TITLE
Positioning and stem of Pie chart labels

### ISSUE THREAD

**Issue by gajus** [FormidableLabs/victory#1323] opened 2019-06-15 11:55 UTC
# Feature Requests

This is a request for a better label component to use with pie charts.

Pretty much the only method I have seen that allows to fit many slices on a Pie Chart is using labels offset by X from the pie chart (right-aligned), their Y position set near middle of the slice, adjusted not to overlap with other labels, and using long stem to indicate to which slice the label belongs, e.g.

![unnamed](https://user-images.githubusercontent.com/973543/59551104-5cf04180-8f6c-11e9-9951-7e82b68eae12.png)

It would be nice if Victory supported a label component out of the box that enabled this functionality. Presently, it is easier to use another library just for Pie charts than to retrospectively fit the above logic into `VictoryPie`.

Related to:

* https://github.com/FormidableLabs/victory/issues/363
* https://github.com/FormidableLabs/victory/issues/669
* https://github.com/FormidableLabs/victory/issues/414

**Comment by nick-vfip** [comment] 2019-12-18 08:28
@boygirl Any updates on this? Or any alternate methods we can use to resolve it?

**Comment by bhargav11-crest** [comment] 2020-07-14 07:16
@boygirl any progress so far or any alternative, we can use?

**Comment by becca-bailey** [comment] 2022-02-15 21:38
This is a duplicate of #363

**Closed by becca-bailey** 2022-02-15 21:38 UTC
Labels: feature request :pencil2:, help wanted :hammer:, duplicate :dancers:
