### ISSUE TITLE
Using domainPadding in VictoryChart component generates multiple console.errors

### ISSUE THREAD

**Issue by jperkelens** [FormidableLabs/victory#458] opened 2016-12-19 14:57 UTC
When I supply the VictoryChart component with a domainPadding option it generate multiple Invalid propr errors on the VictoryChart and Stack, Axis, and Bar child components. However, I cannot reproduce this in binJS. Enclosed find a screenshot of the errors. Currently using victory 0.14.1.

<img width="1280" alt="screen shot 2016-12-19 at 9 55 06 am" src="https://cloud.githubusercontent.com/assets/176702/21317058/839c86ac-c5d1-11e6-8a50-4dda551e8794.png">

**Comment by boygirl** [comment] 2016-12-19 21:01
@jperkelens I'm not able to reproduce this locally or in jsfiddle. I'm going to close this comment for now, but I would be happy to re-open it if you can provide a code sample / more specific reproduction of the error.

**Closed by boygirl** 2016-12-19 21:01 UTC

**Comment by jperkelens** [comment] 2017-01-05 23:32
@boygirl Yeah VictoryCharts and react-measure were not playing well in some subtle ways, I fixed it on my own, thanks!

**Comment by jefffriesen** [comment] 2017-03-29 23:15
@jperkelens I'm running into this same problem. How did you fix it?

**Comment by jefffriesen** [comment] 2017-03-30 17:21
Well, I fixed it using [sizeMe](https://github.com/ctrlplusb/react-sizeme) instead of `react-measure`
