### ISSUE TITLE
Problem with VictoryVoronoiContainer Example

### ISSUE THREAD

**Issue by vrepsys** [FormidableLabs/victory#1105] opened 2018-08-28 17:07 UTC
The documentation says: "VictoryVoronoiContainer .. will add the active prop to data and label components closest to the current mouse position."

It points to this example: https://formidable.com/open-source/victory/gallery/voronoi-tooltips-grouped/

However, when the mouse cursor is between two right-most points of both lines - all points of the red scatter plot become activated.

I have a very similar unexplained behaviour in my own chart.

<img width="450" alt="chart" src="https://user-images.githubusercontent.com/1429012/44738523-e332b880-aafd-11e8-9493-ec1a8225b46f.png">

**Comment by AlexandreArpin** [comment] 2018-10-12 18:44
Has there been any progress on this?

We're currently still experience the issue.

It'd be happy to provide some help but I'm gonna need some pointers in order to do so.

**Comment by danreeves** [comment] 2018-11-15 22:22
In case it's helpful, I found a workaround for this issue. Adding `name` props to the Line and Scatter components, where the two Scatters have the same name, gives the intended effect.

Modified example code:

```diff
<VictoryChart
  height={400}
  width={400}
  containerComponent={<VictoryVoronoiContainer />}
>
  <VictoryGroup
    color="#c43a31"
    labels={d => `y: ${d.y}`}
    labelComponent={<VictoryTooltip style={{ fontSize: 10 }} />}
    data={[
      { x: 1, y: -3 },
      { x: 2, y: 5 },
      { x: 3, y: 3 },
      { x: 4, y: 0 },
      { x: 5, y: -2 },
      { x: 6, y: -2 },
      { x: 7, y: 5 }
    ]}
  >
    <VictoryLine 
+		name="line-1" 
	/>
    <VictoryScatter
+      name="scatters"
      size={(d, a) => {
        return a ? 8 : 3;
      }}
    />
  </VictoryGroup>
  <VictoryGroup
    labels={d => `y: ${d.y}`}
    labelComponent={<VictoryTooltip style={{ fontSize: 10 }} />}
    data={[
      { x: 1, y: 3 },
      { x: 2, y: 1 },
      { x: 3, y: 2 },
      { x: 4, y: -2 },
      { x: 5, y: -1 },
      { x: 6, y: 2 },
      { x: 7, y: 3 }
    ]}
  >
    <VictoryLine 
+		name="line-2" 
	/>
    <VictoryScatter
+      name="scatters"
      size={(d, a) => {
        return a ? 8 : 3;
      }}
    />
  </VictoryGroup>
</VictoryChart>
```

**Comment by danreeves** [comment] 2018-11-16 00:20
I didn't get to the bottom of it but it looks like somewhere along the way the data is getting merged incorrectly and you end up with scatter data with `continious: true` and the other scatter data get's lost? Like:

```
[
  {_voronoiX: 1, _voronoiY: -3, eventKey: 0, childName: "chart-group-0-line-0", continuous: true, …},
  ...
  {_voronoiX: 1, _voronoiY: -3, eventKey: 0, childName: "chart-group-0-scatter-1", continuous: undefined, …},
  ...
  {_voronoiX: 1, _voronoiY: 3, eventKey: 0, childName: "chart-group-0-scatter-1", continuous: true, …},
  ...
  {_voronoiX: 1, _voronoiY: 3, eventKey: 0, childName: "chart-group-1-line-0", continuous: undefined, …},
  ...
]
```

**Comment by AlexandreArpin** [comment] 2018-11-20 21:57
@danreeves you have solved my issue! I wasn't giving a name attribute to my lines and plots.

Thanks a lot for your input! It has solved my issue :)

**Comment by becca-bailey** [comment] 2022-02-15 01:39
This doesn't appear to be reproducible in the latest version of Victory. PRs are still welcome if you are still experiencing this issue!

**Closed by becca-bailey** 2022-02-15 01:39 UTC
