### ISSUE TITLE
Victory tooltip as labelComponent doesn't work

### ISSUE THREAD

**Issue by Adam-isdd** [FormidableLabs/victory#1703] opened 2020-10-05 17:27 UTC
I made clear create-react-app folder and installed Victory. 

"react": "^16.13.1",
"react-dom": "^16.13.1",
"react-scripts": "3.4.3",
"victory": "^35.1.1"

I tried it on all my browser and it doesn't render any tooltip on hover.

When i tried this on forked sandbox, it worked.
https://codesandbox.io/s/peaceful-wilbur-v3fs0?file=/index.js:63-116

Is this some kind of magic?

```
import React from 'react'
import { VictoryBar, VictoryTooltip } from 'victory'

import './App.css'

function App() {
  return (
    <div className="App">
      <VictoryBar
        labels={({ datum }) => 'devet'}
        style={{ labels: { fill: 'red' } }}
        labelComponent={<VictoryTooltip />}
      />
    </div>
  )
}

export default App
```

**Comment by boygirl** [comment] 2020-10-05 20:56
That should be all that is required to make it work. I'm not able to reproduce the issue you're seeing, but you can test whether it is a problem with the events, or some different layout problem by adding the  `active` prop to `VictoryTooltip`, which will make it always show up. If you add that prop, and the tooltips show up where you expect them to, you will know the events either aren't firing correctly or aren't being attached to the `Bar` components.

**Comment by boygirl** [comment] 2020-10-08 16:45
@Adam-isdd I'm guessing this might be related to https://github.com/FormidableLabs/victory/issues/1702

**Comment by boygirl** [comment] 2020-10-08 21:58
closing as duplicate of https://github.com/FormidableLabs/victory/issues/1702

**Closed** 2020-10-08 22:00 UTC
Labels: unverified
