### ISSUE TITLE
Choppy animation when going from 0 to 100

### ISSUE THREAD

**Issue by seripap** [FormidableLabs/victory#653] opened 2017-07-14 15:55 UTC
Expected (running @v0.19.0)
https://jsfiddle.net/excellent/fbpg18sd/

Issue reproduced (running @v0.21.1)
https://jsfiddle.net/excellent/6e3uj1p5/

Animation is ok when numbers are not zero
https://jsfiddle.net/excellent/mg7m69sp/

**Comment by boygirl** [comment] 2017-07-17 21:15
@seripap this one might take some digging on my part, but I notice that if you set an explicit domain for y, the issue goes away.

**Comment by DraGonM** [comment] 2019-11-27 12:22
I also came across this issue, for now instead of `0` using `0.1` =( 
PS: I round values in `Label`, so labels still showing 0's

**Comment by beccanelson** [comment] 2021-11-02 21:38
I'm not currently able to reproduce this issue. Since there hasn't been any discussion on this issue in a few years, I'm going to close this for now in an effort to clean up some of our older issues. Let me know if it needs to be re-opened!

**Closed by beccanelson** 2021-11-02 21:38 UTC
