### ISSUE TITLE
Export PropTypes as CustomPropTypes

### ISSUE THREAD

**Issue by lucasbento** [FormidableLabs/victory#760] opened 2017-09-25 14:03 UTC
Using `PropTypes` from `react` package is deprecated, therefore we need to import it from [prop-types](https://github.com/facebook/prop-types), by using a [react codemod](https://github.com/reactjs/react-codemod/blob/master/transforms/React-PropTypes-to-prop-types.js) to update the code the following happens:

![image](https://user-images.githubusercontent.com/6207220/30812344-c6a81806-a20a-11e7-8d8c-dc0cdbae5c15.png)

I would open an issue on react-codemod repository since it removes part of this import: https://github.com/FormidableLabs/victory-pie/blob/master/src/components/victory-pie.js#L6 but it doesn't make much sense, it seems that every victory project imports `PropTypes` and uses it as `CustomPropTypes`, it would be better to simply export it as `CustomPropTypes`.

**Comment by ryan-roemer** [comment] 2017-09-25 16:01
We've already migrated to importing from `prop-types` instead of `React.PropTypes`.

I think the confusion is you're looking at **Victory's** prop types, not Reacts. What you're pointing to is:

https://github.com/FormidableLabs/victory-core/blob/master/src/index.js#L34

```js
export { default as PropTypes } from "./victory-util/prop-types";
```

which points to: https://github.com/FormidableLabs/victory-core/blob/master/src/victory-util/prop-types.js

If you find any actual React.PropTypes definitely let us know, but I'm pretty confident we've upgraded all of them. Thanks!

**Comment by ryan-roemer** [comment] 2017-09-25 16:06
@lucasbento -- Can you create a small reproduction repository with install / build steps to show me the problem? The codemod _looks_ like it's tailored to only correctly mutating `React` prop types, so I'd like to debug exactly what is going wrong with the codemod.

**Comment by lucasbento** [comment] 2017-10-03 09:40
@ryan-roemer: really sorry for the late response and thanks for replying back.

1. Clone these repositories in your machine:
https://github.com/reactjs/react-codemod & https://github.com/FormidableLabs/victory-pie.

2. Install jscodeshift:
```sh
yarn add jscodeshift --global
```

3. Run codemod on victory-pie:
```sh
jscodeshift -t /path/to/react-codemod/transforms/React-PropTypes-to-prop-types.js /path/to/src/components/victory-pie.js
```

4. See the `git diff` of `src/components/victory-pie.js`: 
```sh
git diff /path/to/src/components/victory-pie.js
```

Which outputs:

```diff
 import React from "react";
 import PropTypes from "prop-types";
 import { partialRight } from "lodash";
-import {
-  addEvents, Helpers, Data, PropTypes as CustomPropTypes, Slice,
-  VictoryContainer, VictoryLabel, VictoryTheme
-} from "victory-core";
+import { addEvents, Helpers, Data, Slice, VictoryContainer, VictoryLabel, VictoryTheme } from "victory-core";
 import PieHelpers from "./helper-methods";
```

**Comment by ryan-roemer** [comment] 2017-11-20 21:14
Confirmed. This is my diff:

```diff
diff --git a/src/components/victory-pie.js b/src/components/victory-pie.js
index 707348b..1cfa017 100644
--- a/src/components/victory-pie.js
+++ b/src/components/victory-pie.js
@@ -2,10 +2,7 @@
 import React from "react";
 import PropTypes from "prop-types";
 import { partialRight } from "lodash";
-import {
-  addEvents, Helpers, Data, PropTypes as CustomPropTypes, Slice,
-  VictoryContainer, VictoryLabel, VictoryTheme
-} from "victory-core";
+import { addEvents, Helpers, Data, Slice, VictoryContainer, VictoryLabel, VictoryTheme } from "victory-core";
 import PieHelpers from "./helper-methods";
 
 const fallbackProps = {
```

**Comment by ryan-roemer** [comment] 2017-11-20 21:26
Debugging the issue, I **think** this is all that is needed in: https://github.com/reactjs/react-codemod at transforms/React-PropTypes-to-prop-types.js

```diff
diff --git a/transforms/React-PropTypes-to-prop-types.js b/transforms/React-PropTypes-to-prop-types.js
index b6f777c..d1d2426 100644
--- a/transforms/React-PropTypes-to-prop-types.js
+++ b/transforms/React-PropTypes-to-prop-types.js
@@ -220,7 +220,8 @@ module.exports = function(file, api, options) {
       .find(j.Identifier)
       .filter(path => (
         path.node.name === 'PropTypes' &&
-        path.parent.node.type === 'ImportSpecifier'
+        path.parent.node.type === 'ImportSpecifier' &&
+        path.parent.parent.node.source.value === 'react'
       ))
       .forEach(path => {
         hasModifications = true;
```

@lucasbento -- would you be up for maybe opening a PR against https://github.com/reactjs/react-codemod or at least an issue against them since it seems to be an upstream issue and nothing specific to Victory (?)

/cc @boygirl

**Comment by boygirl** [comment] 2018-10-03 04:33
Closing this issue due to lack of continued interest

**Closed by boygirl** 2018-10-03 04:33 UTC
