### ISSUE TITLE
tooltip doesn't show at current possition when setting orientaion to "left".

### ISSUE THREAD

**Issue by alishir** [FormidableLabs/victory#801] opened 2017-10-19 06:12 UTC
![screenshot_2017-10-19_09-30-17](https://user-images.githubusercontent.com/978306/31756622-d169c640-b4b1-11e7-89d7-d83782262bb6.png)

**Comment by narinluangrath** [comment] 2018-12-07 22:35
Seems to be caused by the default padding of 10 on the style object for labels. Setting the padding to 0 fixes the issue, but causes gridlines to show up. codesandbox.io/s/30mnr18pj1

**Comment by FergusDevelopmentLLC** [comment] 2019-10-15 20:15
Hello, I just discovered your excellent library and am attempting to tackle this issue:

It looks like the default label (padding: 10) in baseLabelStyles, from victory-core/src/victory-theme/grayscale.js...

```
// *
// * Labels
// *
const baseLabelStyles = {
  fontFamily: sansSerif,
  fontSize,
  letterSpacing,
  padding: 10, //<<<<<<<<<<
  fill: charcoal,
  stroke: "transparent"
};

scatter: assign(
    {
      style: {
        data: {
          fill: charcoal,
          stroke: "transparent",
          strokeWidth: 0
        },
        labels: baseLabelStyles //<<<<<<<<<<
      }
    },
    baseProps
  ),
```

...gets applied to dy in victory-core/victory-util/label-helpers.js in the getOffset(props, datum) function, based on getPadding(props, datum) call...

```
function getOffset(props, datum) {
  if (props.polar) {
    return {};
  }
  const padding = getPadding(props, datum);
  return {
    dx: padding.x,
    dy: padding.y
  };
}
```
For a proposed fix, I added check in getPadding(props, datum) so that if the label component is VictoryTooltip, don't use the default padding...
(original lines commented out below)

```
function getPadding(props, datum) {
  datum = datum || {};
  //const { horizontal, style } = props;
  const { horizontal, style, labelComponent } = props;
  const labelStyle = style.labels || {};
  //const defaultPadding = Helpers.evaluateProp(labelStyle.padding, props) || 0;
  const defaultPadding = Helpers.evaluateProp(labelComponent.type.name, props) === "VictoryTooltip" ? 0 : Helpers.evaluateProp(labelStyle.padding, props) || 0;
  const sign = datum._y < 0 ? -1 : 1;
  return {
    x: horizontal ? sign * defaultPadding : 0,
    y: horizontal ? 0 : -1 * sign * defaultPadding
  };
}
```
As a check, in my [App.js](https://github.com/FergusDevelopmentLLC/victory-issue-801/blob/master/src/App.js), I am not adding dy=0 to the VictoryScatter component, and tooltip works properly with orientations (top, left, right, bottom). If I remove labelComponent alltogether, the static label correctly gets the default padding applied and the label appears above the point.

```
<div>
    <VictoryScatter
    style={{ parent: parentStyle }}
    labelComponent={
        <VictoryTooltip 
        //dy={0} 
        orientation={'left'}
        />
    }
    labels={({ datum }) => `hi #${datum.x}`}
    size={({ active }) => (active ? 5 : 3)}
    data={[{ x: 3, y: 3 }]}
    />
</div>
```
Proposed fix: 
https://github.com/FergusDevelopmentLLC/victory-issue-801/blob/master/src/victory-core/src/victory-util/label-helpers.js
update the getPadding(props, datum) function

Github repo with the proposed fix: https://github.com/FergusDevelopmentLLC/victory-issue-801
Codesandbox: https://codesandbox.io/s/github/FergusDevelopmentLLC/victory-issue-801

**Comment by boygirl** [comment] 2019-10-21 19:04
@FergusDevelopmentLLC 
Thanks for taking an interest and looking into this issue! I think your solution is not quite right, however, and would introduce a breaking change for folks who are expecting padding to alter the dy of their orientation="top" labels. I think the better solution would be to alter either the `getPadding`  function in `label-helpers` so that when there is an `orientation` prop is given, the padding is only applied on the proper side. Right now, there is a check for the `horizontal` prop that  but I think there also needs to be a check for orientation. Does that make sense?

**Comment by FergusDevelopmentLLC** [comment] 2019-10-22 16:42
Thank you for responding. I think I understand what you mean and tbh, I was not keen on relying on labelComponent.type.name to be "VictoryTooltip". I will take a closer look soon.

**Comment by FergusDevelopmentLLC** [comment] 2019-10-24 19:22
Hi,
I took a look again and wanted to be clear on the breaking change introduced by the proposed fix that you mention. But, I can't seem to find and issue when altering dy of "top" oriented labels with the proposed fix in place. Here is what I see:
![image](https://user-images.githubusercontent.com/1529796/67517013-ea504a80-f65e-11e9-9d6c-5d303e0807bd.png)
These seem to be behaving correctly, as the dy override is followed. I also checked that other 3 orientations behave in the same manner. That being said, I still plan to approach again with your suggestion of an additional `orientation` prop because I think this prop could eliminate reliance on `labelComponent.type.name === "VerticalTooltip"` in the proposed fix.

Also, when you mention 'orientation="top" labels', you are referring to a `<VictoryTooltip>`, not a `<VictoryLabel>`, correct? Reviewing the docs, it appears that the `orientation` prop applies to `<VictoryTooltip>,` not `<VictoryLabel>`. I see there is labelPlacement on a VictoryLabel, but that doesn't seem to be the same.
Thanks!

Here is my `VictoryScatter`, that contains the `VictoryTooltip`:

```
<VictoryScatter
  style={{ parent: parentStyle }}
  labelComponent={<VictoryTooltip orientation={'top'} dy={100} />}
  labels={({ datum }) => `hi #${datum.x}`}
  size={({ active }) => (active ? 5 : 3)}
  data={[{ x: 3, y: 3 }]}
/>
```

**Comment by boygirl** [comment] 2019-10-24 20:18
@alishir the breaking change would be the padding no longer influencing the `dy` value for tooltips. So there are a few different things going on here:

1) "left" and "right" orientation tooltips are getting vertical rather than horizontal padding. This is a bug that should be addressed by checking for the `orientation` prop and changing which padding is applied. I would not consider the fix for this bug a breaking change.

2) It's not clear whether padding should alter the tooltip `dy` position at all. Currently it does, but maybe this is undesireable. I think I'm convinced of that, and willing to change that behavior, but this will be create a small breaking change, and will need to be addressed in the next major version bump. we tend to batch our breaking changes, and if we introduced this one, I would want to take the opportunity to look at label padding and positioning more generally.

I think thing 1 is what this issue was originally about, but we can also talk about cleaning up the confusion around padding vs dy/dx more generally if you're interested.

**Comment by FergusDevelopmentLLC** [comment] 2019-10-25 14:43
@boygirl I think I understand what you mean with the orientation prop. I will take a closer look this way. Also, definitely interested to help clean up confusion. Do you prefer connecting on the Spectrum chat or continue here?

**Comment by boygirl** [comment] 2019-10-25 19:37
Let's continue chatting here for now. I'll do some thinking about the more general label padding confusion.

**Comment by FergusDevelopmentLLC** [comment] 2019-10-28 18:08
I took a closer look, and I think I have a fuller understanding now. I understand the purpose of the [horizontal](https://formidable.com/open-source/victory/docs/common-props#horizontal) prop, and I can see that the default 10px padding is intentional and should follow the horizontal and orientation props.

Can you confirm in the actual/expected examples below, that my expected versions are the as you expect?

Note...
1. The previous proposed fix code was not included when producing examples below.
2. The expected screenshots below were created by overriding dy/dx.
3. I did not capture my cursor when capturing the screenshots for clarity.

thanks!

---

1. orientation on VictoryTooltop labelComponent = **‘top’**
VictoryScatter horizontal = **false**
```
<VictoryScatter
  size={5}
  labelComponent={<VictoryTooltip orientation={'top'} />}
  labels={({ datum }) => `(${datum.x}, ${datum.y})`}
  data={[{ x: 3, y: 1} , {x: 3, y: 2 } ]}
  horizontal={false}
/>
```
![image](https://user-images.githubusercontent.com/1529796/67700987-b46bd880-f974-11e9-9d24-f8ac5473e0cc.png)

---

2. orientation on VictoryTooltop labelComponent = ‘**top**’
VictoryScatter horizontal = **true**
```
<VictoryScatter
  size={5}
  labelComponent={<VictoryTooltip orientation={'top'} />}
  labels={({ datum }) => `(${datum.x}, ${datum.y})`}
  data={[{ x: 3, y: 1} , {x: 3, y: 2 } ]}
  horizontal={true}
 />
```
![image](https://user-images.githubusercontent.com/1529796/67701832-47f1d900-f976-11e9-8d26-0e5ad45ee51e.png)

---

3. orientation on VictoryTooltop labelComponent = ‘**left**’
VictoryScatter horizontal = **false**
```
<VictoryScatter
  size={5}
  labelComponent={<VictoryTooltip orientation={'left'} />}
  labels={({ datum }) => `(${datum.x}, ${datum.y})`}
  data={[{ x: 3, y: 1} , {x: 3, y: 2 } ]}
  horizontal={false}
 />
```
![image](https://user-images.githubusercontent.com/1529796/67701655-f1849a80-f975-11e9-9bc4-9935acae646b.png)

---

4. orientation on VictoryTooltop labelComponent = ‘**left**’
VictoryScatter horizontal = **true**
```
<VictoryScatter
  size={5}
  labelComponent={<VictoryTooltip orientation={'left'} />}
  labels={({ datum }) => `(${datum.x}, ${datum.y})`}
  data={[{ x: 3, y: 1} , {x: 3, y: 2 } ]}
  horizontal={true}
 />
```
![image](https://user-images.githubusercontent.com/1529796/67702236-fc8bfa80-f976-11e9-8b9e-f5d4d9603849.png)

---

5. orientation on VictoryTooltop labelComponent = ‘**bottom**’
VictoryScatter horizontal = **false**
```
<VictoryScatter
  size={5}
  labelComponent={<VictoryTooltip orientation={'bottom'} />}
  labels={({ datum }) => `(${datum.x}, ${datum.y})`}
  data={[{ x: 3, y: 1} , {x: 3, y: 2 } ]}
  horizontal={false}
/>
```
![image](https://user-images.githubusercontent.com/1529796/67702415-52f93900-f977-11e9-96e2-7109cc5a518e.png)

---

6. orientation on VictoryTooltop labelComponent = ‘**bottom**’
VictoryScatter horizontal = **true**
```
<VictoryScatter
  size={5}
  labelComponent={<VictoryTooltip orientation={'bottom'} />}
  labels={({ datum }) => `(${datum.x}, ${datum.y})`}
  data={[{ x: 3, y: 1} , {x: 3, y: 2 } ]}
  horizontal={true}
 />
```
![image](https://user-images.githubusercontent.com/1529796/67702596-9e134c00-f977-11e9-8116-e2e25424e0a4.png)

---

7. orientation on VictoryTooltop labelComponent = ‘**right**’
VictoryScatter horizontal = **false**
```
<VictoryScatter
  size={5}
  labelComponent={<VictoryTooltip orientation={'right'} />}
  labels={({ datum }) => `(${datum.x}, ${datum.y})`}
  data={[{ x: 3, y: 1} , {x: 3, y: 2 } ]}
  horizontal={false}
 />
```
![image](https://user-images.githubusercontent.com/1529796/67702720-df0b6080-f977-11e9-9632-bd2b60f5d503.png)

---

8. orientation on VictoryTooltop labelComponent = ‘**right**’
VictoryScatter horizontal = **true**
```
<VictoryScatter
  size={5}
  labelComponent={<VictoryTooltip orientation={'right'} />}
  labels={({ datum }) => `(${datum.x}, ${datum.y})`}
  data={[{ x: 3, y: 1} , {x: 3, y: 2 } ]}
  horizontal={true}
 />
```
![image](https://user-images.githubusercontent.com/1529796/67702919-31e51800-f978-11e9-88f3-18801acde098.png)

**Comment by boygirl** [comment] 2019-10-28 19:50
@FergusDevelopmentLLC Yes, all of the expected behavior you show looks correct. Thank you for including all the screenshots. They add a ton of clarity!

**Comment by FergusDevelopmentLLC** [comment] 2019-11-06 19:43
@boygirl any thoughts? I would really like to help with this issue or another one. Thanks again for a great library.

**Comment by boygirl** [comment] 2020-07-08 00:38
Apologies folks, but I believe this is fixed in the most recent version

**Closed by boygirl** 2020-07-08 00:38 UTC
Labels: bug, good first issue, help wanted
