### ISSUE TITLE
How to set tickLabels on Axis without repeating?

### ISSUE THREAD

**Issue by AndresTIY** [FormidableLabs/victory#1883] opened 2021-06-16 19:54 UTC
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I expect being able to control the labels being shown on VictoryAxis.

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

The data being used in a series of dates going week to week, with a y value being applied to each one. Looks like:
```
[
{x: "2021-01-02", y: 0},
{x: "2021-01-09", y: 10},
{x: "2021-01-16", y: 20},
{x: "2021-01-23", y: 44},
{x: "2021-01-30", y: 122},
...
]
```
So certain months have 5 weeks instead of 4, so it's uneven a bit. I think because of that, the month of Jan is appearing twice on my chart. Screenshot:

<img width="361" alt="Screen Shot 2021-06-16 at 2 47 01 PM" src="https://user-images.githubusercontent.com/25064365/122283459-2e3a3800-ceb2-11eb-9384-e882bcc6ab1a.png">

I extract the values that the VictoryAxis component is using and then using it in tickValues to test out how to control the amount. The sample array is:

```
  const sample = [
    '2021-01-02',
    '2021-01-09',
    '2021-01-16',
    '2021-01-23',
    '2021-01-30',

    '2021-02-06',
    '2021-02-13',
    '2021-02-20',
    '2021-02-27',

    '2021-03-06',
    '2021-03-13',
    '2021-03-20',
    '2021-03-27',

    '2021-04-03',
    '2021-04-10',
    '2021-04-17',
    '2021-04-24',

    '2021-05-01',
    '2021-05-08',
    '2021-05-15',
    '2021-05-22',
    '2021-05-29',

    '2021-06-05',
    '2021-06-12',
  ];
```

The tickCount is set to 6. 

Is it possible to prevent the **Jan** label from showing twice?

Bonus: 
June is part of the sample data yet it's not being shown on the graph. Is it possible to display it?

**Comment by beccanelson** [comment] 2021-06-21 21:48
Hi @AndresTIY, thanks for calling out this issue! Would it be possible for you to create a sandbox reproduction that includes any axis formatting logic you are using? I'm not able to reproduce the same issue, but it could be something weird happening with the scaling and axis formatting. In my example, Victory is grouping the axis labels by month without any repeats.

https://codesandbox.io/s/victory-month-axis-demo-tslly

**Comment by beccanelson** [comment] 2021-06-21 22:50
Closing this issue for now, though it may be worth re-visiting linear vs. time scaling for string-formatted dates in the future.

**Closed by beccanelson** 2021-06-21 22:50 UTC

**Comment by AndresTIY** [comment] 2021-07-06 17:43
@beccanelson appreciate the help!
So I tried using VictoryGroup and that didn't achieve what I wanted.

Here's a reproducible example though:
```
import React from 'react';
import { View } from 'react-native';
import { VictoryChart, VictoryAxis, VictoryLine } from 'victory-native';

import moment from 'moment';

const graphData = [
  { x: '2021-07-01', y: 155 },
  { x: '2021-06-25', y: 166 },
  { x: '2021-06-24', y: 155 },
  { x: '2021-06-22', y: 155 },
  { x: '2021-06-21', y: 155.5 },
  { x: '2021-06-19', y: 145.5 },
  { x: '2021-06-17', y: 155 },
  { x: '2021-06-03', y: 155 },
];

const timeArray = [
  '2021-06-01',
  '2021-06-02',
  '2021-06-03',
  '2021-06-04',
  '2021-06-05',
  '2021-06-06',
  '2021-06-07',
  '2021-06-08',
  '2021-06-09',
  '2021-06-10',
  '2021-06-11',
  '2021-06-12',
  '2021-06-13',
  '2021-06-14',
  '2021-06-15',
  '2021-06-16',
  '2021-06-17',
  '2021-06-18',
  '2021-06-19',
  '2021-06-20',
  '2021-06-21',
  '2021-06-22',
  '2021-06-23',
  '2021-06-24',
  '2021-06-25',
  '2021-06-26',
  '2021-06-27',
  '2021-06-28',
  '2021-06-29',
  '2021-06-30',
  '2021-07-01',
  '2021-07-02',
  '2021-07-03',
  '2021-07-04',
  '2021-07-05',
  '2021-07-06',
  '2021-07-07',
  '2021-07-08',
  '2021-07-09',
  '2021-07-10',
  '2021-07-11',
  '2021-07-12',
  '2021-07-13',
  '2021-07-14',
  '2021-07-15',
  '2021-07-16',
  '2021-07-17',
  '2021-07-18',
  '2021-07-19',
  '2021-07-20',
  '2021-07-21',
  '2021-07-22',
  '2021-07-23',
  '2021-07-24',
  '2021-07-25',
  '2021-07-26',
  '2021-07-27',
  '2021-07-28',
  '2021-07-29',
  '2021-07-30',
  '2021-07-31',
  '2021-08-01',
  '2021-08-02',
  '2021-08-03',
  '2021-08-04',
  '2021-08-05',
  '2021-08-06',
  '2021-08-07',
  '2021-08-08',
  '2021-08-09',
  '2021-08-10',
  '2021-08-11',
  '2021-08-12',
  '2021-08-13',
  '2021-08-14',
  '2021-08-15',
  '2021-08-16',
  '2021-08-17',
  '2021-08-18',
  '2021-08-19',
  '2021-08-20',
  '2021-08-21',
  '2021-08-22',
  '2021-08-23',
  '2021-08-24',
  '2021-08-25',
  '2021-08-26',
  '2021-08-27',
  '2021-08-28',
  '2021-08-29',
  '2021-08-30',
  '2021-08-31',
];

const ChartWeightExpirement = () => {
  const handleTickFormat = (t: string) => {
    return moment(t).format('MMM');
  };
  return (
    <View accessibilityLabel="Chart">
      <VictoryChart domainPadding={{ y: 30 }}>
        {/* horizontal axis lines && y axis */}

        <VictoryAxis
          style={{
            grid: {
              stroke: 'grey',
              strokeWidth: 2,
            },
            axis: { stroke: 'transparent' },
            tickLabels: {
              fontSize: 12,
              lineHeight: 18,
            },
          }}
          dependentAxis
        />

        {/* x axis with tick marks */}
        <VictoryAxis
          style={{
            axis: { stroke: 'transparent' },
          }}
          domainPadding={40}
          tickFormat={(t) => handleTickFormat(t)}
          tickValues={timeArray}
          tickCount={3}
        />

        {/* graph line */}
        <VictoryLine
          name="Line1"
          interpolation="catmullRom"
          data={graphData}
          style={{
            data: {
              stroke: 'grey',
              strokeWidth: 5,
              strokeLinecap: 'round',
            },
          }}
        />
      </VictoryChart>
    </View>
  );
};

export default ChartWeightExpirement;

```
