### ISSUE TITLE
VictoryBar: paddings are not calculated correctly

### ISSUE THREAD

**Issue by mgreca** [FormidableLabs/victory#1236] opened 2019-01-22 12:11 UTC
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

We are having issues to show bar charts with a few bars.
We want the bars to have the same width than the spaces, and the domainPadding to be the half of them. Unfortunately Victory is not calculating correctly this for charts with less than 5 bars. 

### Reproduction

You can see the error in https://codesandbox.io/s/w7ypryz667 
We have a chart with 500px width and the area where the bars are is 400px. We set the bars width to 100px and the domainPadding x to 100px, so we should have:
- 50px first domainPadding
- 100px first bar
- 100px space
- 100px second bar
- 50px last domainPadding.

But this is not happening as you can see in the sandbox link, the space in the middle is bigger, and the domainpadding are shorter. We were working on this several days and we think is a Victory issue because for charts with more or equal than 5 bars, it shows correctly

**Comment by boygirl** [comment] 2019-04-08 21:17
I'm closing this issue as a duplicate of https://github.com/FormidableLabs/victory/issues/472

**Closed by boygirl** 2019-04-08 21:18 UTC
