### ISSUE TITLE
ZoomContainer blows up if axis has tickValues that don't start and end at the zoomDomain.

### ISSUE THREAD

**Issue by jdalegonzalez** [FormidableLabs/victory#919] opened 2018-02-05 18:24 UTC
I set tickValues on the X axis with `tickValues={[0, 1000]}` because it was the recommended way to get a tick mark at the beginning (0) and at the end of the axis.  Any zooming when tickValues is set on an axis that can zoom will result in:
```
add-events.js:210 Uncaught TypeError: Cannot read property 'axis' of undefined
    at addEvents.getComponentProps (add-events.js:210)
    at addEvents.renderLine (victory-axis.js:50)
    at addEvents.render (victory-axis.js:148)
    at finishClassComponent (react-dom.development.js:7873)
    at updateClassComponent (react-dom.development.js:7850)
    at beginWork (react-dom.development.js:8225)
    at performUnitOfWork (react-dom.development.js:10224)
    at workLoop (react-dom.development.js:10288)
    at HTMLUnknownElement.callCallback (react-dom.development.js:542)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:581)
    at invokeGuardedCallback (react-dom.development.js:438)
    at renderRoot (react-dom.development.js:10366)
    at performWorkOnRoot (react-dom.development.js:11014)
    at performWork (react-dom.development.js:10967)
    at batchedUpdates (react-dom.development.js:11086)
    at batchedUpdates (react-dom.development.js:2330)
    at dispatchEvent (react-dom.development.js:3421)
```

The work-around (fix?) is to trap the onZoomDomainChange event and reset tickValues based on the new values in zoomDomain.   However, figuring out that was what was causing the problem wasn't easy.  At a minimum, a better log message would help.

**Comment by becca-bailey** [comment] 2022-02-15 01:19
I'm closing for now since there is a good chance this has been resolved in a more recent version. If this has not been resolved, please re-open with a reproduction.

**Closed by becca-bailey** 2022-02-15 01:19 UTC
