### ISSUE TITLE
Tooltip jitter on mouseover

### ISSUE THREAD

**Issue by coreylight** [FormidableLabs/victory#439] opened 2016-11-30 21:45 UTC
The tooltip created from `VictoryVoronoiTooltip` seems to jitter in and out on mouseover.
https://jsfiddle.net/alikhani/kk1kftoq/

Browser:
http://whatsmybrowser.org/b/INITK0E

**Comment by borkxs** [comment] 2016-12-07 00:25
Noticed this myself. It's reproducible in the examples.

![victoryflutter](https://cloud.githubusercontent.com/assets/1069580/20949300/9e58cd10-bbe6-11e6-9420-d63be4cf7689.gif)

It looks something like `onMouseEnter` renders a tooltip under the cursor, the new tooltip obstructs the event target, `onMouseLeave` fires hiding the tooltip. I tried adding `labels: { pointerEvents: "none" }` to the styles but I think that only applies to the text of the tooltip.

**Comment by borkxs** [comment] 2016-12-07 00:35
Ehh, actually that might be a slightly different issue. I thought there might have been an issue with the way you used multiple Veronoi components but it still happens when I tried combining the data points on a single component](https://jsfiddle.net/x5k8bozg/). And it looks like it still jitters even if you don't mouse directly over the tooltip.

![victoryflutter2](https://cloud.githubusercontent.com/assets/1069580/20949977/a0e7dc70-bbea-11e6-864f-f2d843edc7b7.gif)

**Comment by MrNice** [comment] 2016-12-09 22:23
@coreylight See #446 and check if that helps

**Comment by boygirl** [comment] 2016-12-13 19:13
@coreylight @MrNice The solution proposed in #446 has been implemented and released in `victory@0.14.1`

**Closed by boygirl** 2016-12-13 19:13 UTC
