### ISSUE TITLE
Animation desync between `VictoryAxis` and `VictoryBar` wrapped in `VictoryChart` when domain changes

### ISSUE THREAD

**Issue by rudasoftware** [FormidableLabs/victory#850] opened 2017-11-21 00:47 UTC
Descriptive title is descriptive.

I have a single `animate` prop set on a `VictoryChart` which contains a `VictoryAxis` and a `VictoryBar`. The data have positive and negative values. When the dataset changes, and the new domain has the zero-line at a different position inside the range, the Axis animates at a different rate than the baseline of the Bars.

The difference is most pronounced when the change in zero-line is large, but the desync is evident even in small changes if you look closely.

Likely related, if the difference is large enough, the bars seem to "freeze" while the rest of the chart is animating, snapping quickly to position toward the end of the duration. Sometimes, it looks like they snap to the new position instantaneously, but I'm pretty sure they're still lerping. Just very, very quickly.

**Comment by rudasoftware** [comment] 2017-11-21 00:49
[2017-11-17 13-53-26_mov.zip](https://github.com/FormidableLabs/victory/files/1489618/2017-11-17.13-53-26_mov.zip)

Apologies for the video file. Better than gif, probably, but not as convenient.

**Comment by rudasoftware** [comment] 2017-11-21 00:50
Reproduced in v0.24.2

**Comment by beccanelson** [comment] 2021-11-02 21:59
Since there hasn't been any discussion on this issue in a few years, I'm going to close this for now in an effort to clean up some of our older issues. Let me know if it needs to be re-opened, and I'll try to get an updated reproduction.

**Closed by beccanelson** 2021-11-02 21:59 UTC
