### ISSUE TITLE
transforms for dataComponents should be pre calculated

### ISSUE THREAD

**Issue by mattoni** [FormidableLabs/victory#784] opened 2017-10-05 23:22 UTC
Every pie chart i've tried making is rendering strangely. It has the bottom right quadrant visible in the top left corner, and the rest rendered out of the container:

![image](https://user-images.githubusercontent.com/5110855/31256711-1a71b308-a9e9-11e7-94ff-1b6f6532e5b0.png)

Here's the rendered html:
![image](https://user-images.githubusercontent.com/5110855/31256720-2d927c2e-a9e9-11e7-8f5f-884d8510b3a3.png)

And the react code used to generate it:
![image](https://user-images.githubusercontent.com/5110855/31256728-381ce3aa-a9e9-11e7-9ae1-dc96718794f6.png)

I'm probably missing something obvious, but any help is greatly appreciated. Thanks!

**Comment by mattoni** [comment] 2017-10-05 23:27
adjusting the viewbox to -200 -200 400 400 fixes it, and I notice all the demo charts have a translate(-200, -200) on them.

**Comment by boygirl** [comment] 2017-10-06 02:46
@mattoni what version of Victory are you on? 

Recent versions have moved from translating the whole pie, to translating individual slices, so you should see that translation on your path elements. From the html you posted, I'm not seeing that translation on your path elements or on the g tag surrounding them. I would guess you have some strange version skew going on.

**Comment by mattoni** [comment] 2017-10-06 04:43
hi @boygirl,

I just updated to v0.23.1. It did change the top level svg to a div. It's still having the same issue. 

![image](https://user-images.githubusercontent.com/5110855/31263275-12997800-aa16-11e7-987a-358445ef59a1.png)

![image](https://user-images.githubusercontent.com/5110855/31263285-1f8f8482-aa16-11e7-9023-d71f0da66bd1.png)

I manually added the translation to the svg for a hacky fix and that works, but this shouldn't be necessary from the sound of it. Let me know what other data I can get you.

**Comment by boygirl** [comment] 2017-10-11 00:52
@mattoni sorry for the delay. I'm still not able to reproduce this issue. Not seeing any transform end up on your path suggests that something is going very wrong with your Slice dataComponent. What happens if you remove the dataComponent prop? The only other thought I have is that setting your width to 1000 without setting a height may be causing some odd rendering. This would result in a 4:1 aspect ratio for your svg. VictoryPie won't ever render an ellipse, though, so it will size your pie, and attempt to center it in that container unless you specifically provide a padding prop. What happens if you remove the width?

**Comment by mattoni** [comment] 2017-10-11 22:03
Hi no problem, we're all busy :)

I didn't consider it could be my slice component causing issues. I believe we are using a custom slice component so that might be the issue. I'll play with it this week and see what happens. Thanks so much!

**Comment by boygirl** [comment] 2017-10-27 02:27
@mattoni I'm going to close this issue, as I suspect is has to do with a custom data component. Please let me know if you have further questions.

**Comment by mattoni** [comment] 2017-10-27 05:06
Actually I do. The issue arises when using a dataComponent and creating a custom slice. If I pass all the props down into my new component, it is off center like above. It seems to be missing the transform to correctly adjust the custom component's offset. There is an origin {x, y } prop passed down that matches, so I did 

```
transform={`translate(${origin.x},${origin.y})`}
```

and that worked. I didn't see any of this in the documentation so I'm not sure if it's covered somewhere I missed.

Thanks!

**Comment by boygirl** [comment] 2017-10-27 21:58
@mattoni good point. Maybe these should all be passed down as `transform` already calculated so that they get properly applied without users having to know that detail. I'll reopen this issue with an edited title

**Closed** 2019-06-11 17:36 UTC
