### ISSUE TITLE
Tick value spacing and null data gaps not working with VictoryChart, custom axes and VictoryGroup

### ISSUE THREAD

**Issue by Cryptolemming** [FormidableLabs/victory#644] opened 2017-07-07 15:29 UTC
Hi, very cool library :).  Was tasked with evaluating and selecting viz toolkits at work - tried Recharts, ReactD3 and Victory Charts.  Victory Charts by a landslide - it has been very fun to work with too.

Am facing a couple challenges.  The spacing of my tick values and the null data gap are not functioning well with custom axes.  Please see here:

<a href="https://ibb.co/ftrffF"><img src="https://thumb.ibb.co/ftrffF/Screen_Shot_2017_07_07_at_8_18_50_AM.png" alt="Screen Shot 2017 07 07 at 8 18 50 AM" border="0" /></a>

The X Axis values for 6/5/2017 and 6/8/2017 are null - I think they are causing the skewed tick representation, here is my configuration:

```      
render() {
        const styles = this.getStyles();
        const data = this.getData();
        const domain = this.getDomain(data);
        const tickFormat = this.getTickFormat(data);
        const tickValues = this.getTickValues(data);
        const avgY = this.getAvgY(data);
        const annotation = this.props.annotation;

        return (

            <VictoryChart
                width={this.props.width}
                height={this.props.height}
                containerComponent={<VictoryContainer responsive={false} />}
                style={styles.parent}
                offsetX={100}
                scale={{x:"time", y:"linear"}}
            >

                <VictoryAxis
                    style={styles.XAxis}
                    orientation="bottom"
                    label="Date"
                    // Todo: tickValues => large tick for Day, small ticks for hours within
                    tickFormat={tickFormat}
                    tickValues={tickValues}
                />

                <VictoryAxis
                    dependentAxis
                    style={styles.YAxis}
                    // Todo: max domain from data - leave out domain and include tickValues for tick values as range
                    domain={domain.y}
                    orientation="left"
                    label={this.props.yLabel}
                />

                <VictoryLine
                     style={styles.annotationLine}
                     data={[
                       {x: domain.x[0], y: annotation},
                       {x: domain.x[1], y: annotation}
                     ]}
                     domain={domain}
                     labels={["${this.props.annotation}"]}
                     labelComponent={<VictoryLabel renderInPortal dx={20} dy={20}/>}
                />

                <VictoryLine
                     style={styles.avgLine}
                     data={[
                       {x: domain.x[0], y: avgY},
                       {x: domain.x[1], y: avgY}
                     ]}
                     domain={domain}
                />

                <VictoryGroup data={data} domain={domain}>

                    <VictoryLine
                        style={styles.dataPlotLine}
                        interpolation="linear"
                     />

                    <VictoryScatter
                        style={styles.dataPlotScatter}
                        size={5}
                        labels={(d) => d.y}
                        labelComponent={<VictoryTooltip/>}
                          events={[{
                            target: "data",
                            eventHandlers: {
                              onClick: () => {

                                alert("you clicked a data point");

                                return [{
                                  mutation: (props) => {

                                  }
                                }];
                              }
                            }
                          }]}
                    />

                </VictoryGroup>

            </VictoryChart>

        );
    }

    getData() {
        let chartData = this.props.data.map((currentObject, currentIndex) => {
                return { x: currentObject.date, y: currentObject[this.props.metric] };
           });

        return chartData;
    }

    getDomain(data) {
        console.log(data);
        let maxX = data[data.length - 1].x;
        let minX = data[0].x;
        let maxY = data
                       .map((object) => { return object.y })
                       .reduce((max, cur) => { return Math.max(max, cur) });
        let minY = data
                       .map((object) => { return object.y })
                       .reduce((min, cur) => { return Math.min(min, cur) });

        let domain = { x: [minX, maxX], y: [0, maxY] };

        return domain;
    }

    getTickFormat(data) {
        let range = this.props.selectedRange.range;
        let rangeSelector = AppConstants.RangeSelectorValues;

        if (range === rangeSelector.ONE_DAY
            || (range === rangeSelector.CUSTOM
            && rangeInDays(selectedRange.start, selectedRange.end) < AppConstants.HOURLY_PLOT_DAY_THRESHOLD)) {

            return this.getTickFormatHourly(data);
        }

        return this.getTickFormatDaily(data);
    }

    getTickFormatHourly(data) {
        let tickFormat = data.map((currentObject, currentIndex) => {
            let date = currentObject.x;
            let dateFormat = date.toLocaleDateString();
            let dateHour = hoursAsString(date);
            let isFirstPoint = currentIndex === 0 ? true : false;

            if (isFirstPoint || dateHour === AppConstants.ShopperHours.DAY_START) {
                return dateHour + "\n" + dateFormat;
            }

            return dateHour;
        });

        return tickFormat;
    }

    getTickFormatDaily(data) {
        let tickFormat = data.map((currentObject, currentIndex) => {
            let date = currentObject.x;
            let dateFormat = date.toLocaleDateString();

            return dateFormat;
        });

        return tickFormat;
    }

    getTickValues(data) {
        let tickValues = data.map((currentObject, currentIndex) => {
            return currentObject.x;
        });
        console.log(tickValues);
        return tickValues;
    }
```

Also the VictoryLabel in VictoryLine is not displaying - I mean for the blue and red horizontal lines to have labels to the right which display their values (those values will change).  Not sure if that has something to do with my sizing - am having difficulty with sizing and centering of the charts.  Have looked through the issues here and StackOverflow and can't seem to center the charts within the container am placing them in.  Would like the charts to grow horizontally with their container as well while maintaining their height if that is possible. 

Thank you for any help or guidance :)

**Comment by boygirl** [comment] 2017-07-07 17:29
Hi there, I'm glad you're enjoying Victory.

tickValues:
I hadn't considered null tick values. Is there a reason for including them in your array of tickValues rather than filtering them out? 

Labels on VictoryLine:
supplying a single value for your `labels` prop for VictoryLine will cause your label to be displayed next to your first point. It looks like you already figured out how to move it around with `dx` and `dy` props on `VictoryLabel`, you can also absolutely position it with `x` and `y`. Maybe try sticking them in the middle of the chart that way to make sure they're showing up at all? 

Sizing:
Victory renders responsive containers by default with the `viewBox` attribute, and `width: "100%" height: "100%"`. The width and height props on `VictoryChart` (or other top level Victory component) will affect the aspect ratio of the chart. Having charts grow only horizontally would require a resize handler that updated the width / height props as you would need to change the aspect ratio of your chart.

I'm going to close this issue, but I will continue to answer questions on the issue. Creating a JSFiddle with a reproduction of your issue would also be really helpful. You can alter one of mine to get started: https://jsfiddle.net/boygirl/0wLd9b2f/ You can also try the gitter channel for support. I'm there pretty often. https://gitter.im/FormidableLabs/victory

**Closed by boygirl** 2017-07-07 17:29 UTC

**Comment by Cryptolemming** [comment] 2017-07-07 20:23
Hi thank you for responding so quickly this is a huge help! :)

tickValues:  
Sorry I didn't communicate that well.  The tick values will be present and gaps in the data plotting are required.  All is well with some changes I made  - except - even if including all the days, still get some skewing, not sure why - also the scatter plot point still shows even though that y value is null.

<a href="https://ibb.co/kcpsua"><img src="https://thumb.ibb.co/kcpsua/Screen_Shot_2017_07_07_at_1_06_57_PM.png" alt="Screen Shot 2017 07 07 at 1 06 57 PM" border="0" /></a>

Labels o VictoryLine:
good news is it is rendering :) bad news is it seems my width is cut off - I think can improve that by adding domain padding to the X Axis?  Not sure if that is the best route however?

<a href="https://ibb.co/iTBoZa"><img src="https://thumb.ibb.co/iTBoZa/Screen_Shot_2017_07_07_at_1_14_18_PM.png" alt="Screen Shot 2017 07 07 at 1 14 18 PM" border="0" /></a>

I would like to achieve this:  https://github.com/FormidableLabs/victory/issues/633

Sizing:
The sizing of the container vs sizing of the resulting svg vs the aspect ratio relationship is still confusing to me to be honest.  The width and height I am providing the VictoryContainer component is influencing the size - now if I were to set responsive=true in the container - the aspect ratio of the custom width and height I provided will influence both the width and height.  Still unclear how to achieve 3 things:
1 - The width and height of the chart should be a % of my parent wrapper component for the Victory Chart
2 - Center the chart within that parent wrapper component
3 - Maintain that same ratio in relation to the wrapper component when the wrapper component changes size - that means if the wrapper component is only growing horizontally (which is all they are doing) then the chart grows with it, maintaining the same height.

Would love to join on Gitter - won't be able to on work laptop however will be there from work laptop when possible.  Thanks!

**Comment by boygirl** [comment] 2017-07-08 18:42
tickValues:
The skewing may be due to your tickValues. If they are date objects, they will be placed exactly where they should on the time scale axis. Maybe some of those date objects are not exactly 24 hours apart? That's my best guess as to what is going on.

labels on VictoryLine: 
you have a couple options... You can increase the padding on your chart so that your labels have more room, or you can render your labels in to the top level portal provided by any of the Victory container components (used by default). To to this add `labelComponent={<VictoryLabel renderInPortal/>}` to `VictoryLine`

Centering stuff:
I'm not sure exactly what you're after, but this fiddle should be helpful: https://jsfiddle.net/boygirl/p7rsgmrh/1/

**Comment by Cryptolemming** [comment] 2017-07-10 18:24
Thank you for taking the time to help.  

tickValues:
You're right, it is because they are not 24 hours apart - tried searching the docs for a solution to that but couldn't find one.  Is there a way to assure equidistant ticks?  

labels on VictoryLine:
I tried both methods, regardless the labels are not rendering to the right of the table and lines.  This is what I have:  

`
                <VictoryLine
                     style={styles.annotationLine}
                     data={[
                       {x: domain.x[0], y: annotation},
                       {x: domain.x[1], y: annotation}
                     ]}
                     domain={domain}
                     labels={["label"]}
                     labelComponent={<VictoryLabel renderInPortal x={'95%'} y={100} />}
                />
`

Is it also possible to extend the blue and red horizontal lines to the right a bit as well, then to display the label beside the extension?

Centering and ratio:
Awesome thanks used Flexbox and charts are now centered in their containers :).  Is it possible for the chart to only have a responsive width with a fixed height?  I have the following as my top level component:
`
            <VictoryChart
                width={this.props.width}
                height={this.props.height}
                containerComponent={<VictoryContainer responsive={true} />}
                style={styles.parent}
            >
`
The charts will maintain the aspect ratio for the width and height have provided - wondering if it's possible to achieve responsive width but fixed height?

Thank you
