### ISSUE TITLE
Charts blocks page scroll on mobile-web

### ISSUE THREAD

**Issue by nighto** [FormidableLabs/victory#1430] opened 2019-11-01 20:13 UTC
# Bugs and Questions

### Checklist

- [X] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Victory Charts blocks scroll on mobile (tested on iPhone Safari). 

### Reproduction

For instance, opening [Victory Gallery page](https://formidable.com/open-source/victory/gallery/) on mobile browser (tested with iPhone Safari). It is only possible to scroll the page dragging outside of the charts; if you drag inside the chart, the page scroll is blocked. This of course makes it impossible or very hard to scroll when your page has several full-width, full-height scrolls.

# Feature Requests

### Checklist

- [X] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

IMHO if a Chart has no drag/scroll event it should not block the scroll. Or, at least, have an option to disable this behaviour.

What I have tried, following #1037:

```jsx
<svg width='100%' height='50%'>
    <VictoryChart standalone={false} />
</svg>
```

This however makes the chart not responsive anymore, but at least would not block scroll. Of course this would not be ideal. Is there a better solution?

Please notice I am **not** using react-native, therefore workarounds proposed on #1037 like adding a surrounding `<View />` or `<Svg />` wouldn't apply.

**Comment by SamambaMan** [comment] 2019-11-01 20:16
Same issue here!

**Comment by ursulac** [comment] 2019-11-12 10:33
Same issue here

**Comment by ursulac** [comment] 2019-11-12 12:09
The issue does not happen for me on the latest Safari on desktop or iPhone (latest updates), but does happen on Android Samsung internet browser and Android Firefox/Chrome. 
I tried the svg solution and it didn't work, I also tried a CSS hack `svg * { pointer-events: none }` but it didn't work either.

**Comment by martapa** [comment] 2020-01-30 20:56
I had the same problem. It seems like the Victory library sets user-select, pointer-events, and touch-action properties with a value of none, as inline CSS. This workaround worked for me:
`VictoryContainer {
user-select: auto !important;
pointer-events: auto !important;
touch-action: auto !important;
}`

**Comment by ursulac** [comment] 2020-02-18 14:40
@martapa that worked for me, thank you

**Comment by thefilmmaking** [comment] 2020-04-05 19:57
@martapa solution works great, but also blocks user events in the browser. As a workaround, I just wrapped that solution in a CSS `@media` rule to only trigger it under 600px (can be adjusted accordingly):

```
@media only screen and (max-width: 600px) {
    .VictoryContainer {
        user-select: auto !important;
        pointer-events: auto !important;
        touch-action: auto !important;
    }
}
```

**Comment by selsamman** [comment] 2020-04-09 19:57
@martapa That seems to do it on Android.  I don't think there was a problem on IOS.  Thanks so much.  Saved me so much time.  The easy way tell when Formidable fixes the problem is to just launch their docs in the Android browser and place your finger of a graph.  No joy scrolling.

**Comment by narinluangrath** [comment] 2020-05-03 03:27
This is a duplicate of #1037. Here's a solution to this problem: https://github.com/FormidableLabs/victory/issues/1037#issuecomment-623048143

The css solutions mentioned above should also work.

**Closed by narinluangrath** 2020-05-03 03:27 UTC

**Comment by LouisLoiseau** [comment] 2022-03-09 15:13
Nope not working. pointerEvents and userSelect are omitted and touchAction is overriden.
