### ISSUE TITLE
Could data-testids be added to the graph?

### ISSUE THREAD

**Issue by joenarus** [FormidableLabs/victory#2171] opened 2022-03-25 20:15 UTC
# Questions

Is there a way to add test ids to things like the bar, or area fills? 
It would be awesome to be able to test these values with ui-test frameworks like cypress/jest.

**Comment by becca-bailey** [comment] 2022-03-29 16:54
Hi @joenarus, this is a duplicate of https://github.com/FormidableLabs/victory/issues/2040, and there are some open PRs to address this.

**Closed by becca-bailey** 2022-03-29 16:54 UTC
Labels: duplicate :dancers:
