### ISSUE TITLE
have a strange behaviour here, when i move out the mouse from the Victory Chart, the tooltip does not disappear, only disappears 

### ISSUE THREAD

**Issue by sindhu465** [FormidableLabs/victory#943] opened 2018-03-16 16:01 UTC
# Bugs and Questions

### Checklist

* [ ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

* [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by sindhu465** [comment] 2018-03-16 16:03
Could you Please let me know how to hide the tooltip label on mouse out from the graph.
my tooltip is still displaying even if I remove my mouse pointer.
I am using VictoryVoroniContainer.

labels={(d) =>{return d.x+'\npredicted:'+d.y} }
 labelComponent={<VictoryTooltip Style={{ fontSize: 13 }}
 pointerLength={(d) => d.y > 2165 ? 7: 40} />}
 containerComponent={<VictoryVoronoiContainer/>}

**Comment by boygirl** [comment] 2018-06-24 06:11
I am not able to reproduce this issue in the latest version. I am closing this issue for now

**Closed by boygirl** 2018-06-24 06:11 UTC
