### ISSUE TITLE
VictoryLine creates path with NaN and fail to render

### ISSUE THREAD

**Issue by gartz** [FormidableLabs/victory#796] opened 2017-10-16 05:02 UTC
Here is the console log:

```
 Data:  (47) [0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.49333, 0.53333, 0.66667, 0.67, 0.65, 0.66, 0.66, 0.57, 0.69333, 0.58333, 0.58333, 0.55333, 0.43, 0.43, 0.74667, 0.55, 0.55, 0.87, 0.85333, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909, 0.00909]0: 0.009091: 0.009092: 0.009093: 0.009094: 0.009095: 0.009096: 0.009097: 0.009098: 0.009099: 0.0090910: 0.0090911: 0.0090912: 0.0090913: 0.0090914: 0.0090915: 0.0090916: 0.0090917: 0.0090918: 0.0090919: 0.0090920: 0.4933321: 0.5333322: 0.6666723: 0.6724: 0.6525: 0.6626: 0.6627: 0.5728: 0.6933329: 0.5833330: 0.5833331: 0.5533332: 0.4333: 0.4334: 0.7466735: 0.5536: 0.5537: 0.8738: 0.8533339: 0.0090940: 0.0090941: 0.0090942: 0.0090943: 0.0090944: 0.0090945: 0.0090946: 0.00909length: 47__proto__: Array(0) Domain:  {x: Array(2), y: Array(2)}x: (2) [27, 47]y: (2) [0.00909, 0.87]__proto__: Object
vendor-dddbc47cd4918d8a9539.js:12 Error: <path> attribute d: Expected number, "….34932478762886,NaNC-258.9826581…".
setValueForAttribute @ vendor-dddbc47cd4918d8a9539.js:12
setValueForProperty @ vendor-dddbc47cd4918d8a9539.js:12
updateProperties @ vendor-dddbc47cd4918d8a9539.js:12
commitUpdate @ vendor-dddbc47cd4918d8a9539.js:12
commitWork @ vendor-dddbc47cd4918d8a9539.js:12
l @ vendor-dddbc47cd4918d8a9539.js:12...
vendor-dddbc47cd4918d8a9539.js:12 Error: <path> attribute d: Expected number, "….56233405282705,NaNC-259.1956673…".
```

As you can see, the data contains 47 number elements, the domain x and y are valid values.

I have a `domainPadding: [1, 4]` and the size of the chart is: `width: 208, height: 62`. I'm using `linear` animation.

I can't find why it's not working, and it's quite hard to reproduce sometimes.

It also seems to have the same problem if all the data contains the same number, instead of drawing a straight path, it does NaN and fails.

**Comment by boygirl** [comment] 2017-10-16 22:23
@gartz 

Victory expects data as an array of objects. You can use an array like that if you specify data accessors `x` and `y`.  Can you alter [this fiddle](https://jsfiddle.net/boygirl/sjf9zymz/) to reproduce what you're seeing?

Thanks!

**Comment by boygirl** [comment] 2017-10-27 02:28
@gartz I'm going to close this issue, as I can't reproduce it. Please let me know if your problem persists or if you have other questions.

**Closed by boygirl** 2017-10-27 02:28 UTC

**Comment by nemosupremo** [comment] 2018-08-23 21:04
I'm hitting the same issue, when I set a domainPadding. Not sure if I'm using this parameter correctly.

https://jsfiddle.net/sjf9zymz/32/

**Comment by boygirl** [comment] 2018-08-23 22:06
@nemosupremo try setting `domainPadding` on your top-level victory component (VictoryChart)

**Comment by nemosupremo** [comment] 2018-08-23 22:28
That worked, thanks

**Comment by MZeeshan373** [comment] 2024-01-08 09:23
@boygirl Thanks. It worked for me.
