### ISSUE TITLE
Regression: Tooltip do not work with CRA typescript

### ISSUE THREAD

**Issue by mak-elena** [FormidableLabs/victory#1511] opened 2020-04-15 08:47 UTC
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

I'm using victory charts in CRA (typescript) app.
I tried to use tolltips with several charts, but the tooltips are not dispayed.
Although when I leave standard labels they are rendered correctly. 
Versions of packages:
    "@types/react": "16.9.11",
    "@types/react-dom": "16.9.4",
    "@types/victory": "^33.1.4",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-scripts": "3.4.1",
    "typescript": "3.8.3",
    "victory": "^34.1.3"

### Reproduction

* Clone this repository [victory-tooltip](https://github.com/mak-elena/victory-tooltip) with a sample. This is just a standard CRA typescript App with a tooltips example copied from here: https://formidable.com/open-source/victory/guides/tooltips#simple-tooltips
* install & start
* Actual result: Tooltips are not shown when mouse hovers bars.
* Expected result: tootips are dispplayed when hover bars

**Comment by maddles** [comment] 2020-04-17 00:07
Looks like events aren't triggering prop changes in CRA apps.

This repros with both .js and .tsx extensions, and appears to be present only in CRA apps.

From investigation it appears mutation functions in the component event handlers are invoked, and setState is being called with the correct parsed eventReturn in victory-util/events.js, but component props aren't being updated. Continuing investigation.

**Comment by mak-elena** [comment] 2020-05-19 09:38
Hi, @maddles  do you have any update to the issue?

**Comment by lederer** [comment] 2020-06-05 13:22
Same problem here. CRA app (JS, not Typescript). Even when just pasting in code from [a gallery example](https://formidable.com/open-source/victory/gallery/voronoi-tooltips-with-grouped-components), the VictoryTooltip's `active` prop never gets set.

**Comment by SnareHanger** [comment] 2020-07-07 21:45
I had the same issue with a CRA app.  Removing the `<React.StrictMode>` tag in App.jsx/tsx reinstates the tooltip functionality.  This probably shouldn't be a fix, but it's a workaround.

**Comment by junhyuk-prestolabs** [comment] 2020-09-07 10:12
Same here, any updates?

**Comment by junhyuk-prestolabs** [comment] 2020-09-08 06:33
Oh, I found.
In my case it requires `VictoryVoronoiContainer`

```
      <VictoryChart
        containerComponent={<VictoryVoronoiContainer />}
        width={1194}
        height={320}
        padding={{ left: 0, top: 0, right: 60, bottom: 20 }}
        scale={{ x: 'time' }}
        animate={{ duration: 300 }}
      >
        <VictoryArea
          labelComponent={<VictoryTooltip />}
          data={chartDataWithLabel}
        />
```

And tooltips shown.

**Comment by boygirl** [comment] 2020-10-08 21:58
closing as duplicate of https://github.com/FormidableLabs/victory/issues/1702

**Closed** 2020-10-08 22:00 UTC
