### ISSUE TITLE
scale.x is not a function when embedding Line

### ISSUE THREAD

**Issue by isitrita** [FormidableLabs/victory#1112] opened 2018-09-13 09:15 UTC
Hi, I am trying to draw box, which will be looked as grid which will be bounded from four sides with grey 
<img width="630" alt="screen shot 2018-09-13 at 12 12 14" src="https://user-images.githubusercontent.com/1010119/45479178-6edb5480-b74e-11e8-997e-341f14d31a35.png">

I am trying to put `Line` to do that, but I get exception `TypeError: scale.x is not a function
    at Object.scalePoint (helpers.js:108)`
How I could do that?

```     <VictoryChart
        scale={{ x: 'time' }}
        polar={false}
        height={166}
        padding={{
          top: 20,
          bottom: 30,
          left: 20,
          right: 50,
        }}
        theme={theme}
        containerComponent={
          <VictoryVoronoiContainer
            voronoiDimension="x"
            labels={d => `${d.y} ${new Date(d.x).toLocaleDateString()}`}
            labelComponent={<Tooltip />}
          />
        }
      >
        <VictoryAxis independentAxis />
        <VictoryAxis orientation="right" tickCount={6} dependentAxis />
        <Line
          x1="20"
          x2="20"
          y1="136"
          y2="20"
          role="presentation"
          shapeRendering="auto"
          vectorEffect="non-scaling-stroke"
          style={{stroke: 'rgba(73, 75, 82, 0.17)', strokeWidth: 1}}
        />
        {
          <VictoryGroup data={toDisplay} domain={domain}>
            <VictoryArea
              interpolation="monotoneX"
              style={{
                data: {
                  stroke: '#486de8',
                  strokeWidth: '1',
                  fill: '#486de829',
                },
              }}
            />
          </VictoryGroup>
        }
      </VictoryChart>```

**Comment by boygirl** [comment] 2018-09-13 15:17
@isitrita 
I'm not able to reproduce the issue you're seeing. Is your <Line/> component from `react-native-svg`?

I made a codesandbox with an example of embedding a line within a chart: https://codesandbox.io/s/v3x6w4y345

I'm going to close this issue for now, but I will reopen it if you can help me come up with a reproducible failing test case. Please feel free to edit that codesandbox to get started.

If you're not able to make that fail, and you this the issue you're seeing is specific to Victory Native, please open an an issue here instead: https://github.com/FormidableLabs/victory-native/issues

**Closed by boygirl** 2018-09-13 15:17 UTC
