### ISSUE TITLE
Docs page broken

### ISSUE THREAD

**Issue by VladimirPittner** [FormidableLabs/victory#986] opened 2018-04-24 15:23 UTC
### The Problem

Victory Docs page http://formidable.com/open-source/victory/docs is broken.

### Reproduction

If I click on VictoryPie chart in navigation I get this:
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at t (bootstrap aeee59dc48a09d88d137:52)
    at docs-victory-pie.json?215c:9
    at loader.js:116
    at loader.js:71
    at u.run (browser.js:153)
    at s (browser.js:123)
```
```
Uncaught TypeError: Cannot read property 'slug' of undefined
    at t.render (docs.js:12)
    at f._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:796)
    at f._renderValidatedComponent (ReactCompositeComponent.js:819)
    at f._updateRenderedComponent (ReactCompositeComponent.js:743)
    at f._performComponentUpdate (ReactCompositeComponent.js:721)
    at f.updateComponent (ReactCompositeComponent.js:642)
    at f.receiveComponent (ReactCompositeComponent.js:544)
    at Object.receiveComponent (ReactReconciler.js:122)
    at f._updateRenderedComponent (ReactCompositeComponent.js:751)
    at f._performComponentUpdate (ReactCompositeComponent.js:721)
```
If I try to go to gallery I get this
```
(index):1 GET http://formidable.com/open-source/victory/app-a7923be6ecff7630130f.js net::ERR_ABORTED
(index):1 GET http://formidable.com/open-source/victory/path---gallery-7dcefaba187f656004b8.js net::ERR_ABORTED
(index):91 GET http://formidable.com/open-source/victory/app-a7923be6ecff7630130f.js net::ERR_ABORTED
(anonymous) @ (index):91
(anonymous) @ (index):91
(index):91 GET http://formidable.com/open-source/victory/path---gallery-7dcefaba187f656004b8.js net::ERR_ABORTED
```

**Comment by boygirl** [comment] 2018-04-24 17:11
@VladimirPittner Yep, we're working on it. Sorry for the inconvenience. I'm going to close this issue, but we are very aware of the problem.

**Closed by boygirl** 2018-04-24 17:11 UTC

**Comment by boygirl** [comment] 2018-04-24 20:36
The underlying issue is https://github.com/gatsbyjs/gatsby/issues/1043 Still working on a resolution, but the intermittent nature of the issue is making it quite difficult
