### ISSUE TITLE
Unable to use Victory Chart

### ISSUE THREAD

**Issue by gauravbhusare** [FormidableLabs/victory#390] opened 2016-10-12 10:42 UTC
I am trying to use victory chart, I tried with empty chart, then also it is giving me following error.
I just rendered `<VictoryChart />`.

        helper-methods.js:12 Uncaught TypeError: _react2.default.Children.toArray is not a function

Please help me solving this issue.

**Comment by boygirl** [comment] 2016-10-13 18:26
@gauravbhusare I'm not able to reproduce this issue
https://jsfiddle.net/boygirl/6zLu49wo/

Can you provide a little more context? Version numbers?

**Comment by gauravbhusare** [comment] 2016-10-14 09:29
@boygirl 

react@0.13.3
react-dom@15.3.2
victory@0.10.4

I think this is the issue because of react version.

**Comment by boygirl** [comment] 2016-10-16 18:58
@gauravbhusare yes, I think you could be right. Are you able to upgrade to react 15? Also, the latest version of victory is 0.13. I'm really happy to help with the latest versions, but since this is alpha software, I'm not really committed to supporting old versions.

**Closed by boygirl** 2016-10-16 18:58 UTC
