### ISSUE TITLE
Voronoi Container Tooltip is displaying the wrong data

### ISSUE THREAD

**Issue by seriously-sian** [FormidableLabs/victory#1251] opened 2019-02-14 15:36 UTC
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

With a dual Y axis graph, we are attempting to use a VoronoiContainer to give us a tooltip. We are seeing the date in the tooltip is incorrect and is often displayed twice. I can understand it being displayed twice due to the two lines - but it does make it frustrating. The incorrect date is more annoying as this is causing the tooltip to display the wrong data for that date.

### Reproduction
We have reproduced the issue: https://codesandbox.io/s/llqj7zwmv7

**Comment by becca-bailey** [comment] 2022-02-15 01:53
This is possibly a duplicate of #1925

**Closed by becca-bailey** 2022-02-15 01:53 UTC
