### ISSUE TITLE
VictoryStack is not padding single point domains

### ISSUE THREAD

**Issue by jacargentina** [FormidableLabs/victory#1042] opened 2018-07-10 18:12 UTC
# Bugs and Questions

### Checklist

* [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory
`0.27.2`
* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Getting a warning. But dont know how to fix; or if there is an error on my use of the library.

```jsx
sandbox.c7332c5c.js:1 Warning: Failed prop type: Invalid prop `domain` supplied to `VictoryBar`.
    in VictoryBar (created by VictoryBar)
    in VictoryAnimation (created by VictoryTransition)
    in VictoryTransition (created by VictoryBar)
    in VictoryBar (created by App)
    in svg (created by VictoryContainer)
    in div (created by VictoryContainer)
    in VictoryContainer
    in VictoryStack (created by App)
    in div (created by App)
    in App

```

### Reproduction

Here https://w6oj6z41lw.codesandbox.io/

Click the "Zero now!" button, and look the console.

**Comment by jacargentina** [comment] 2018-07-10 18:14
I'm sure it is related to the use of animations; if i remove the `animate= ... ` the warning is gone.

**Comment by tomciopp** [comment] 2018-07-19 06:01
I don't believe this is related to the animate prop. I get the same error in the following components `VictoryGroup`, `VictoryAxis`, `VictoryScatter` and `VictoryLine`. None of those are using the animate property on my side. I am using `scale`, `style`, `theme`, `width`, `height`, and `domain`

**Comment by boygirl** [comment] 2018-08-04 04:15
@jacargentina I think the issue is that when you click the "zero now", your dataset has a single data point, and therefore a single point domain x: [0, 0]. Normally Victory components will apply a very small amount of domain padding to prevent a single point domain error. It looks like `VictoryStack` is not applying this padding when setting the domain for its children. I will look into fixing this issue. In the meantime, if you set one of your data values to something like 0.000001 instead of 0 your chart will behave as expected and not throw an error.

P.S. I am updating the title of this issue to reflect new information.

**Comment by becca-bailey** [comment] 2022-02-15 01:24
Closing for now, since I do not believe this is reproducible in the latest version of Victory. Feel free to re-open if this is not the case!

**Closed by becca-bailey** 2022-02-15 01:24 UTC
