### ISSUE TITLE
tooltips on lines don't match interpolated positions

### ISSUE THREAD

**Issue by boygirl** [FormidableLabs/victory#702] opened 2017-08-08 18:48 UTC
As demonstrated in this fiddle from @notsentient

https://jsfiddle.net/pqn3aub8/5/

**Comment by boygirl** [comment] 2019-06-11 06:47
This is because the lines themselves don't cross the actual data points for some interpolations. The tooltips are actually pointing to the _correct_ points. This shows which interpolations have fidelity and which do not: http://bl.ocks.org/emmasaunders/c25a147970def2b02d8c7c2719dc7502

**Comment by becca-bailey** [comment] 2022-02-15 00:41
I'm closing for now since I'm not currently able to reproduce this.

**Closed by becca-bailey** 2022-02-15 00:41 UTC
