### ISSUE TITLE
Bug: Wrong values after animation interpolation in VictoryBar

### ISSUE THREAD

**Issue by orionsa** [FormidableLabs/victory#1280] opened 2019-03-27 13:26 UTC
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x ] I am using the latest version of Victory

- [x ] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem
I am trying to display two bars, the first is the desired value the second is it's complementary.
when rendering VictoryStack and VictoryBars data values after animation interpolation get inaccurate in small numbers as you can see in the bar labels.

### Reproduction
please find two versions one with class the other one with hooks.
https://codesandbox.io/s/5k2wok6nrk

**Comment by boygirl** [comment] 2019-03-27 23:38
@orionsa thanks for the reproduction. It looks like the animation isn't quite completing, but `onEnd` is still being called. I'll take a look.

**Comment by eyalcohen4** [comment] 2019-04-18 07:25
Hi, Is there any update or something we can do to help investigate?

**Comment by orionsa** [comment] 2019-05-02 15:34
@boygirl is there any update regarding this issue?

**Comment by Thembelani** [comment] 2019-10-21 09:39
Good day. Any progress on this issue ?

**Comment by beccanelson** [comment] 2021-11-09 23:26
Currently issues like this one are challenging to address due to some of the complexity around transitions. I'm adding this one to the refactoring milestone so we can make sure we reproduce the desired behavior if we do some refactoring.

**Comment by becca-bailey** [comment] 2022-02-15 01:50
Closing in favor of #2104

**Closed by becca-bailey** 2022-02-15 01:50 UTC
