### ISSUE TITLE
VictoryChart event props bug when wrapped in VictoryZoom

### ISSUE THREAD

**Issue by psunnn** [FormidableLabs/victory#443] opened 2016-12-07 04:23 UTC
First off, I'd like to say thank you for creating this library - as someone who works with React and D3 on a daily basis, this library is the best solution me and my team have come across so far.

When I try to pass in an `events` prop to my `<VictoryChart>` component, I get the following error:
```
Warning: Failed prop type: Invalid prop `events` of type `number` supplied to `VictoryChart`, expected an array
```

My component's render function returns:
```
<VictoryZoom>
  <VictoryChart
    // other props...
    events={[{
      childName: ["a", "b"],
      target: "data",
      eventHandlers: {
        onClick: () => {
          return [
            // ...
          ];
        }
      }
    }]}
  >
    // other Victory components
  </VictoryChart>
</VictoryZoom>
```

But when I look in React DevTools, VictoryChart's `event` props is 2.
<img width="211" alt="screen shot 2016-12-06 at 8 12 17 pm" src="https://cloud.githubusercontent.com/assets/10807627/20954460/6a594792-bbf0-11e6-9742-5a532ac6eab5.png">

To resolve this issue, I removed the `VictoryZoom` component and I'm not getting anymore errors. However, I'm a *big* fan of `VictoryZoom` so I was wondering if there was any way you could resolve this?

**Comment by jevakallio** [comment] 2016-12-08 18:33
@psunnn thanks for reporting this! 

The issue is now fixed in https://github.com/FormidableLabs/victory-chart/pull/420 - will try to get this released soon.

**Closed** 2016-12-08 19:56 UTC
