### ISSUE TITLE
Weird artifacts in small VictoryBar with rounded borders

### ISSUE THREAD

**Issue by rpelorosso** [FormidableLabs/victory#1106] opened 2018-08-31 02:21 UTC
### Checklist

* [x] This is not a `victory-native` specific issue. 

* [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [x] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

When a Bar that has rounded borders is not tall enough, artifacts appear.

![image](https://user-images.githubusercontent.com/6107574/44889102-01e2ac00-acc4-11e8-9c8f-f2c7161a4d5a.png)

### Reproduction

[Here's a sandbox with the issue](https://codesandbox.io/s/7mn851w6mx)

Is there any way to fix this?

thank you!
Rodrigo

**Comment by boygirl** [comment] 2018-09-05 01:13
@rpelorosso thank you for this issue. It's one we're aware of, so I'm going to close it as a duplicate of: https://github.com/FormidableLabs/victory/issues/895

We will need to modify the paths that the `Bar` component is drawing when values are very small. Until we are able to fix this issue, you can provide `cornerRadius` as a function of datum, and reduce the amount of radius used for very short bars.

**Closed by boygirl** 2018-09-05 01:13 UTC
