### ISSUE TITLE
VictoryPie.componentWillMount(): Assigning directly to this.state is deprecated (warning)

### ISSUE THREAD

**Issue by CaryLandholt** [FormidableLabs/victory#741] opened 2017-09-07 02:13 UTC
Using react 16 rc1 and seeing the following warning message in the browser console
```
Warning: VictoryPie.componentWillMount(): Assigning directly to this.state is deprecated (except inside a component's constructor). Use setState instead.
```

Any ideas?
Thanks!

**Comment by zackify** [comment] 2017-09-07 17:17
Getting it too for a few weeks now

**Comment by boygirl** [comment] 2017-09-08 20:23
I'm closing this as a duplicate of https://github.com/FormidableLabs/victory/issues/724

**Closed by boygirl** 2017-09-08 20:23 UTC

**Comment by CaryLandholt** [comment] 2017-09-08 20:31
Ahh. Didn't see that an issue already existed. Cheers!
