### ISSUE TITLE
Horizontal charts do not pan at the correct rate 

### ISSUE THREAD

**Issue by taylorbf** [FormidableLabs/victory#2083] opened 2022-02-04 18:33 UTC
### The Problem

When a chart is set to `horizontal` mode and is zoomed and panned, the panning rate is not 1:1 with mouse movement. 

This appears to occur only if the `height` and `width` of the chart are different.   I wonder if the panning rate is calculated relative to the `height` of the chart when it should be calculated according to the `width` of the chart for left-right panning.   

Suggestions or workarounds welcome.

### Reproduction

https://codesandbox.io/s/autumn-firefly-br1sm?file=/src/App.js

**Comment by becca-bailey** [comment] 2022-02-15 22:47
Hi @taylorbf, thanks for the reproduction! I am seeing these inconsistencies with the way panning is happening in each chart, and I'm uncertain about whether this is intended behavior. I'm not sure whether this issue will be able to be addressed individually, but we are planning to rewrite the zooming behavior sometime in the near future, and I hope that this rewrite will fix some of these smaller inconsistencies. Here's the current ticket where we are tracking issues related to zooming: #2111

**Comment by becca-bailey** [comment] 2022-02-15 22:50
I'm going to close this ticket for now and roll this issue into the rewrite ticket.

**Closed by becca-bailey** 2022-02-15 22:50 UTC

**Comment by TabithaMaudMM** [comment] 2022-04-04 17:59
@becca-bailey I think I have a fix for this bug. Are you currently accepting PRs? 

It looks like getDomainScale is setting the range incorrectly. 
```
  getDomainScale(domain, scale, axis, horizontal) {
    const axisDomain = Array.isArray(domain) ? domain : domain[axis];
    const [from, to] = axisDomain;
    const otherAxis = axis === "x" ? "y" : "x";
    const range = horizontal ? scale[otherAxis].range() : scale[axis].range();
    const plottableWidth = Math.abs(range[0] - range[1]);
    return plottableWidth / (to - from);
  },
```

const range does not need to switch the axis - scale already handles that:
```
  const scale = {
    x: Scale.getBaseScale(props, "x")
      .domain(domain.x)
      .range(props.horizontal ? range.y : range.x),
    y: Scale.getBaseScale(props, "y")
      .domain(domain.y)
      .range(props.horizontal ? range.x : range.y)
  };
```

 So range would just need to be:
```
 const range =  scale[axis].range();
```

This fixes horizontal panning and I don't see any other issues. We need this for a project we're working on, I know this is part of a bigger rewrite ticket but if you're accepting PRs could this be a temporary fix until that bigger ticket is completed?

**Comment by becca-bailey** [comment] 2022-04-04 18:13
@TabithaMaudMM Yes, if you have a fix for now I would love it if you opened a PR.
