### ISSUE TITLE
'bin' is not exported from 'd3-array'

### ISSUE THREAD

**Issue by czmacer** [FormidableLabs/victory#1963] opened 2021-09-10 17:58 UTC
Cannot render any chart due error

./node_modules/victory-histogram/es/helper-methods.js
Attempted import error: 'bin' is not exported from 'd3-array' (imported as 'd3Array').

**Comment by mcserep** [comment] 2021-09-12 11:48
I faced the same issue, only on Windows. I think this is the same as #1822, which was closed unfortunately without dealing with issue.

For me, after some debugging it turned out if I execute in `npm start` or `npm run build` in *PowerShell*, there is no issue, only when using the good old *Command Prompt* of Windows. Since there are separate `.cmd` and `.ps1` scripts in the `.bin` folder of `node_modules`, there could be an issue with the Batch scripts.

If you are also on Windows, maybe try using Powershell.

**Comment by ryan-roemer** [comment] 2021-09-13 02:57
What version of `d3-array` is imported? (Look first in `./node_modules/victory-histogram/node_modules/d3-array/package.json` and then in `./node_modules/d3-array/package.json`)

Also, where is this render happening? Is it in a browser (if so which browser)? Is it in Node.js?

What would be most useful if you could is to create a minimal reproduction repository that includes install + build + error reproduction steps so we can pull it down, follow the steps and see the error. Thanks!

**Comment by becca-bailey** [comment] 2022-02-18 18:54
We have been having some general issues around upgrading d3 packages, which I have opened another issue to resolve. This could be the result of #1878 where we needed to downgrade this package in order to resolve some other dependency issues. I'm going to close this issue since it can't be verified in the current version, but if this is still coming up we can migrate discussion around d3 packages to #2124.

**Closed by becca-bailey** 2022-02-18 18:54 UTC
Labels: needs more info :hand:
