### ISSUE TITLE
Minimum bar height?

### ISSUE THREAD

**Issue by garetmckinley** [FormidableLabs/victory#519] opened 2017-03-15 15:28 UTC
First off just wanna say great work with victory, it's been great to work with so far 😄 

I'm currently working on creating a visualization of activity using a stacked bar chart. The biggest issue I'm running into with victory (aside from the subpixel rendering, which you seem to be taken care of with #345) is that there are no options for a minimum bar height. For this reason, when there is a period of low activity at night (compared to the spikes of incredibly high activity throughout the day) it's literally impossible to see the bars of low activity. Here's an example

 
![screen shot 2017-03-15 at 11 19 54 am](https://cloud.githubusercontent.com/assets/1624279/23955965/c459e46c-0971-11e7-9e7e-2835161db7dd.png)

During the nighttime hours, there's generally 0-100 requests per hour. Compared to 6k/hr, the small values don't even appear on the graph, making it look like there was no activity at all. I'm guessing it's because the calculated height is under 1px.

Is there a solution to this issue currently? If not, do you have any plans to implement some sort of minimum size property to bars?

**Comment by boygirl** [comment] 2017-03-16 00:14
@garetmckinley I think you could use the `domainPadding` prop to solve this issue. 

```
<VictoryChart domainPadding={{ y: [3, 0]}}>
  <VictoryBar data={myData}/>
  ...
</VictoryChart>
```
With the code above, VictoryChart automatically calculate a domain based on the incoming data, and then will pad the y domain by 3px on the minimum end of the domain, so your bars will never be smaller than that.

I'm going to close this issue, but drop me a note in the [gitter channel](https://gitter.im/FormidableLabs/victory) if that doesn't solve your problem.

**Comment by Thom1729** [comment] 2017-05-10 21:20
What about:

```jsx
<VictoryBar
    y={ datum => Math.max(datum.y, 10) }
>
```
If you want a specific pixel value, then just divide the maximum y value in your graph by the height of the graph in pixels.

**Comment by garetmckinley** [comment] 2017-05-10 21:35
I don't think that would work, because that's modifying the actual data, right? So tooltips and stuff would display `10` instead of the actual value

**Comment by boygirl** [comment] 2017-06-28 16:29
After some more thought, I think this one is a "wont fix" for victory. This can be implemented as a one off, however, by creating a custom `dataComponent` that wraps `Bar` and alters the incoming `y` prop when `y` and `y0` are too close together.

**Closed by boygirl** 2017-06-28 16:29 UTC
Labels: feature, improvement

**Comment by RobelTekle** [comment] 2022-01-19 13:10
Hi ! I know this is a very old issue but I cannot find a different solution then the one suggested by @boygirl.
As suggested by @boygirl I used a `Bar` component and I modified the `y` value. The problem is that this will mess with the label position. An example here https://codesandbox.io/s/victory-bar-minimal-size-3now5?file=/src/App.js
Any other suggestion ?

**Comment by androbwebb** [comment] 2022-06-02 15:32
@garetmckinley, @RobelTekle or @vignesh-markkandan - I'd also like to know if you were able to solve this, I have the same issue.

**Comment by RobelTekle** [comment] 2022-06-06 18:06
@androbwebb I was not able to set a min size in px, but I could set a max ratio between the biggest bar and the smallest bars. Instead of editing `y` value I added a new value on the dataset `_minY`. This one is the value with the size correction and it is used to visualize the bar  by victory. The `y` represent the original value and it is used for the label. 
An example here :  

```js
// utils.js
const getDataWithMinBarSize = (data) => {
  const newYKey = '_minY'
  const maxBarRatio = 50

  const values = data.map(({ y }) => y)
  const maxValue = Math.max(...values)

  const dataWithMinBarSize = data.map(d => {
    const isHigherRatio = Math.round(maxValue / d.y) > maxBarRatio

    return {
      ...d,
      [newYKey]: isHigherRatio ? Math.round(maxValue / maxBarRatio) : d.y,
    }
  })

  return [dataWithMinBarSize, newYKey]
}

// Barchart.js

const Barchart = ({ data }) => {

const [barDataWithMinSize, newYKey] = getDataWithMinBarSize(data)
 return (
     <VictoryBar
          data={barDataWithMinSize}
          labels={({ datum }) => datum.y}
          y={newYKey}
        />
 )

}

```

**Comment by malithtennakoon-singlifeph** [comment] 2023-06-13 07:28
You could add a customBar to dataComponent and create custom bar that handle the bars according to the prop data.
`const CustomBar = (props: BarProps) => {
  const value = props?.datum?.value || 0;
  if (value > 0) {
    return <Bar {...props} />;
  } else {
    return <Bar {...props} y0={248} />;
  }
};`
