### ISSUE TITLE
VictoryAxis tickLabelComponent default style issue

### ISSUE THREAD

**Issue by iwan-uschka** [FormidableLabs/victory#1441] opened 2019-11-14 16:51 UTC
# Bugs and Questions

### The Problem

Default styles of a VictoryAxis tickLabelComponent can't be overridden.

### Reproduction

Please have a look at https://codesandbox.io/s/basic-victory-example-itcne. I've defined a customised `VictoryLabel` as `tickLabelComponent` of `VictoryAxis`. A CSS class has been set for this `tickLabelComponent`: `className="chart--axis-tick-label"`. This CSS class looks like:

```
.chart--axis-tick-label {
  font-size: 8px;
  fill: red;
}
```

No value of this class is used because inline styles override everything. But if i set a chart theme like 

```
const theme = {
  axis: {
    style: {
      tickLabels: {
        padding: 5,
        fill: "inherit",
        // fontSize: undefined doesn't work
        fontSize: "inherit",
        stroke: "inherit"
      }
    }
  }
};
```

the fill color from the CSS file is used (because the inline style disappeared) but the font size isn't used because the inline style still appears, no matter what.

I need to set chart styles via CSS.

Thanks for creating such a great library.

**Comment by boygirl** [comment] 2019-11-14 18:24
@iwan-uschka 
The inline styles get merged with styles from Victory's default `theme`. It's using `lodash.defaults`, so undefined values wont work to override values already set on the theme. You can try providing your own theme without those styles set. `VictoryTheme.grayscale` is just an object, so it should be pretty straightforward to extend it and override the offending axis label styling. I'm going to close this issue, but let me know if this solution doesn't work for you.

**Closed by boygirl** 2019-11-14 18:24 UTC

**Comment by iwan-uschka** [comment] 2019-11-21 10:42
Sorry for the delay and thank you for your response!

Unfortunately i don't understand your hint. How can i provide my own theme where the unwanted styles are not merged from Victory's default `theme`? Like you said

> It's using lodash.defaults, so undefined values wont work to override values already set on the theme.

So i guess it won't be possible at the moment to just remove those unwanted styles settings from the theme. And using no theme at all is no solution because the default theme is always used instead.

In the meantime I found a way to override `fontSize` by using `-1` like shown in https://codesandbox.io/s/basic-victory-example-itcne. But it feels hacky because you need position the label manually.

**Comment by boygirl** [comment] 2019-11-26 04:58
Oh! I see what you mean. I think the issue is actually that `VictoryLabel` has a set of default styles. that includes a font size, so this is not actually an issue with the theme. Unfortunately it is necessary to define as an inline style, as `VictoryLabel` uses the font size to calculate positioning to support verticalAnchors and offsets for multi-line labels. I'm not able to drop the default font size for this reason. Apologies!

**Comment by iwan-uschka** [comment] 2019-11-26 08:20
Thanks again for taking the time. Since i was able to override the fontSize using `-1` i am quite happy :) And yes, i fully understand the need of a font size for calculating the position of `VictoryLabel`.

Nevertheless i was wondering why we're able to override any property of theme/default style settings with values not being null/undefined/0 but not able to remove inline styles consistently, regardless of whether further calculation will or won't crash.

Maybe i am not convinced enough of giving up using real CSS files instead of (react-ish) inline styles. In my case it's about theming via CSS files so i am glad that i found a way.

Keep up the good work. Y'all created a great library!!!
