### ISSUE TITLE
Force tooltips to render within chart boundaries

### ISSUE THREAD

**Issue by jhdielman** [FormidableLabs/victory#470] opened 2017-01-05 18:12 UTC
Having an issue trying to render a tooltip for a stacked chart when the stack reaches the top of the chart container. When I hover over top most section of that stack the tooltip is rendered beyond the boundaries and hidden.

**Comment by boygirl** [comment] 2017-01-05 20:30
@jhdielman I'm going to close this issue as a duplicate of https://github.com/FormidableLabs/victory/issues/380. This work is still pretty far out, as constraints have a pretty serious perf overhead. The better thing to do for now is adjust the padding on your chart to accommodate your tooltips.

**Closed by boygirl** 2017-01-05 20:30 UTC

**Comment by jhdielman** [comment] 2017-01-05 20:46
@boygirl Would it be possible to add this as a mutate callback in the tooltip events? This way it has minimal perf impact on the default functionality?

**Comment by boygirl** [comment] 2017-01-05 20:51
@jhdielman I could certainly add tooltip callbacks. Something like `onActivateTooltip` and `onDeactivateTooltip`. I'm not certain you would be able to accomplish what you're after. Would you use these to increase the padding in your chart on the fly? 
Two clarifying questions: 
- What are you hoping to mutate?
- What arguments would you expect these callbacks to take?

**Comment by jhdielman** [comment] 2017-01-05 20:56
Exactly. What I'm hoping do would be to mutate the properties of the tooltip's orientation, dx, dy based on user/developer defined criteria. So perhaps be able to access the instance of the tooltip object using `this` and perhaps the event object as well.

**Comment by boygirl** [comment] 2017-01-05 21:51
@jhdielman Because of how the event system is built, those callbacks wont have access to `this` context, but they already have access to the props of the element that was clicked, the props of the element that will be mutated, and the event object. Since this is already built in, I think what you might actually want is to just use your own events rather than using the `defaultEvents` that `VictoryTooltip` provides. 

Here's a more detailed guide about tooltips, including how to use custom events with tooltips
http://formidable.com/open-source/victory/guides/tooltips/

Here's a deeper look at events
http://formidable.com/open-source/victory/guides/events/

I'm also available in the gitter channel pretty frequently if you have more questions about getting this working. 
https://gitter.im/FormidableLabs/victory

**Comment by jhdielman** [comment] 2017-01-05 22:10
Coolness! Many gracious thanks for your time @boygirl :bow:

**Comment by jamesmcn1** [comment] 2018-06-13 13:12
Hi there - is this feature been added yet?? We dynamically adjust our chart timeline similar to a stock index chart (3 month, 6 month, 1 year, All time etc), so we would need the boundaries to adjust upon cursor change or on filter change
