### ISSUE TITLE
VictoryPie animation stop with wrong values

### ISSUE THREAD

**Issue by berthoug** [FormidableLabs/victory#2991] opened 2024-11-29 12:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Victory version

37.3.2 (the issue is not present in 36.6.11, but present in 36.9.2 and still present in 37.3.2)

### Code Sandbox link

https://codesandbox.io/p/sandbox/piechart-zzgrtl

### Bug report

```markdown
When changing the amount of data and their value in a victory pie the animation ends with a pie in a state that suggests that it took in account the removal of some entries, but not the change of values.
```

### Steps to reproduce

```markdown
- create a pie chart and set the data to `[1, 1, 1, 1, 5]`
- update the data to be `[9, 1, 1, 1]` (in the sandbox, click on the update button)
```

### Expected behavior

```markdown
The animation should end with a pie chart showing four districts, one of which is nine times the size of the others.
```
<img width="515" alt="Screenshot 2024-11-29 at 13 43 25" src="https://github.com/user-attachments/assets/2a5e4451-f9fb-49af-8508-5377bdc0bd24">

### Actual behavior

```markdown
The animation ends up with a pi chart with four equal districts.
```
<img width="566" alt="Screenshot 2024-11-29 at 13 36 47" src="https://github.com/user-attachments/assets/d1bbac1d-8d52-41eb-840e-0ca12b768a9c">

### Environment

```markdown
- Device: laptop
- OS: macos 14.6.1
- Node:v21.6.2
- npm:10.2.4
```

**Comment by djm158** [comment] 2024-12-13 17:15
This looks like a duplicate of https://github.com/FormidableLabs/victory/issues/531

I did leave some notes as to why this specific issue is occurring in the linked PR, but I think we can close this in favor of https://github.com/FormidableLabs/victory/issues/2104

**Closed by djm158** 2024-12-13 17:15 UTC
Labels: Type: Bug :bug:
