### ISSUE TITLE
vitory-native: Metro has encountered an error

### ISSUE THREAD

**Issue by NorfeldtAbtion** [FormidableLabs/victory#2109] opened 2022-02-15 09:57 UTC
# Bugs and Questions

### Checklist

- [X] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [X] I am using the latest version of Victory

- [X] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Following the steps in https://github.com/FormidableLabs/victory/tree/main/packages/victory-native#local-development-and-demo

gives the following error

<img src="https://user-images.githubusercontent.com/53769763/154037280-6c97fec5-6616-4671-a72a-221752223af3.png" width="400"/>

Tried to add `vitory-native` and lastest `react-native-svg`

<img width="678" alt="Screenshot 2022-02-15 at 10 53 27" src="https://user-images.githubusercontent.com/53769763/154037394-16d707ca-6c8d-4cc6-bc61-d613e6286977.png">

**Comment by becca-bailey** [comment] 2022-02-18 18:22
Hi @NorfeldtAbtion, I believe this is a duplicate of some other issues related to react native web. We recently updated our documentation in #2121 to provide some guidance around React native web support with Victory. Let me know if that helps you!

**Closed by becca-bailey** 2022-02-18 18:22 UTC
