### ISSUE TITLE
have a strange behaviour here, when i move out the mouse from the bars, the tooltip does not disappear, only disappears when another one is visible.

### ISSUE THREAD

**Issue by sindhu465** [FormidableLabs/victory#942] opened 2018-03-16 15:39 UTC
# Bugs and Questions

### Checklist

* [ ] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

* [ ] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

* [ ] I am using the latest version of Victory

* [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

* [ ] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

* [ ] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by sindhu465** [comment] 2018-03-16 15:52
Could you Please let me know how to hide the tooltip on mouse out.

**Comment by boygirl** [comment] 2018-04-22 01:11
@sindhu465 

I'm not able to reproduce this behavior in the latest version `victory@0.26.0`. I"m going to close this issue, but if you are still seeing the issue in the latest version, please open another issue with a reproduction

**Closed by boygirl** 2018-04-22 01:11 UTC
