### ISSUE TITLE
VictoryPie doesn't animate and theme doesn't change if animate is set

### ISSUE THREAD

**Issue by stephanemombuleau** [FormidableLabs/victory#841] opened 2017-11-16 15:02 UTC
Hi! First of all, awesome work.

I have an issue with VictoryPie not animating. Nothing fancy going on in the code except:

 ```
<VictoryPie animate={{ duration: 1000, onLoad: { duration: 1500 }, delay: 2000 }} data={data} theme={VictoryTheme.material} />
```

The pie has no animation, and the theme isn't applying.

**If I remove `animate`** the theme does apply...

Any idea?

See fiddle: https://jsfiddle.net/3gLazk66/

**Comment by boygirl** [comment] 2017-11-16 20:01
@stephanemombuleau thanks for the reproduction. I'll get the issues with themes fixed for next week.

**Comment by stephanemombuleau** [comment] 2017-11-17 09:50
@boygirl awesome :) Will the fixes impact animations as well?

**Comment by stephanemombuleau** [comment] 2017-11-20 15:25
After further investigation, it seems that the theme is not applied because VictoryPie doesn't have a `role` set.

Should add in victory-pie.js:
`VictoryPie.role = "pie";`

As for the animation... it seems like the Pie is not ready for transitions.

**Comment by lgerndt** [comment] 2018-03-23 21:30
@stephanemombuleau I too was getting no animation, so I tried your code above, what I see now is that it sorta tries to animate but it all happens in a split second, so something is wrong.  Any further learnings on this?

**Comment by stephanemombuleau** [comment] 2018-03-23 21:41
@lgerndt Not at all. I think the numbers have to relate in some way to your data... It ended not working in most cases (I have a dashboard with multiple charts) so I turned to (react-plotly)[https://github.com/plotly/react-plotly.js/]. It offers more features, better performances and everything works well. It kinda is easier to plug-in as well.

**Comment by AndrewJDick** [comment] 2018-08-13 16:13
Is this any further forward?

**Comment by mattgle** [comment] 2019-10-25 16:47
Claps if it helps :)
https://medium.com/wolox-driving-innovation/how-to-animate-a-pie-chart-with-victory-in-react-native-db5997b991a5

**Comment by beccanelson** [comment] 2021-11-02 22:01
This one seems like a duplicate of https://github.com/FormidableLabs/victory/issues/531.

**Closed by beccanelson** 2021-11-02 22:01 UTC
