### ISSUE TITLE
VictoryZoomContainer dimension="x" doesn't appear to work

### ISSUE THREAD

**Issue by prestond123** [FormidableLabs/victory#640] opened 2017-07-05 14:11 UTC
I'm using victory 0.21 from 
https://cdnjs.cloudflare.com/ajax/libs/victory/0.21.1/victory.min.js

I'm finding that the dimension props is not working on my VictoryZoomContainer, as expected. Chart still pans and zooms in both x, and y dimensions when dimension="x".

Here is how I am using it (3rd line in is my VisctoryZoomContainer): 
```

<VictoryChart height={250}                                        
                    containerComponent={
                        <VictoryZoomContainer dimension="x" />
                    }>
                    <VictoryStack colorScale={colourArray}>
                        {area} 
                    </VictoryStack>
                    <VictoryAxis 
                        fixLabelOverlap={true}
                        scale="time"
                        style={{
                            axis: { stroke: "#756f6a" },                            
                            grid: { stroke: (t) => t === 10 ? "red" : "grey" },
                            ticks: { stroke: "grey" },
                            tickLabels: { fontSize: 8, padding: 5 }
                        }}/>
                    <VictoryAxis 
                        dependentAxis
                        label={yAxesLabel}
                        style={{
                            axis: { stroke: "#756f6a" },
                            axisLabel: { fontSize: 8, padding: 43 },
                            grid: { stroke: (t) => t === 10 ? "red" : "grey" },
                            ticks: { stroke: "grey" },
                            tickLabels: { fontSize: 8, padding: 5 }
                        }}/>
                </VictoryChart>
```

Thanks (Great project BTW)

**Comment by chrisbolin** [comment] 2017-07-05 15:52
hey @prestond123! I used your code to create this fiddle: https://jsfiddle.net/chrisbolin/g0vug9kt/1/, but unfortunately I couldn't reproduce the bug. I had to guess on a few variable (like `area`) that weren't defined in your code. Could you fork the fiddle and modify it so I can see what you do? Thanks!

**Comment by prestond123** [comment] 2017-07-06 08:19
Hi Chris,

Thanks for the speedy response.  I have played around with the fiddle, and
cannot reproduce the issue I'm seeing in development.  I can only conclude
that this is an environment issue, on my side.  Please feel free to close
the issue, and if I can reproduce this in the future, on fiddle, I will let
you know.

I noticed the comment at the top of the code you added:
/* Victory requires `react@^15.5.0` and `prop-types@^15.5.0` */

Our environment is on React 15.4.2, I'll update that shortly.

Thanks and Regards
Dave

**Comment by chrisbolin** [comment] 2017-07-07 10:31
@prestond123 I know that situation, and it can be very frustrating. Let me know if you get more information on the problem, especially if it looks like something we can address in Victory.

On the React/PropTypes front, that comment was included just because we include it with most of our Victory JSFiddles - it's part of the boilerplate :) I don't think you'll see a dramatic change moving to react 15.5.0, but do make sure you include prop-types, as react is removing that from core.

**Closed by chrisbolin** 2017-07-07 10:31 UTC
