### ISSUE TITLE
Centering text inside Victory Pie

### ISSUE THREAD

**Issue by jakubgrzelak** [FormidableLabs/victory#1284] opened 2019-04-02 06:09 UTC
# Bugs and Questions

### Checklist

- [x] This is not a `victory-native` specific issue. (Issues that only appear in `victory-native` should be opened [here](https://github.com/FormidableLabs/victory-native/issues/new))

- [x] I have read through the [FAQ](https://formidable.com/open-source/victory/docs/faq) and [Guides](https://formidable.com/open-source/victory/guides/) before asking a question

- [x] I am using the latest version of Victory

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### The Problem

Describe the issue you're seeing, and what you expect the behavior to be.

### Reproduction

Please try to reproduce the issue you're seeing in a sandbox. You can [fork this sandbox](https://codesandbox.io/s/m3xo745x2x) to get started.

If you can't reproduce your issue in a sandbox, please create a minimal git repo that demonstrates the problem you're seeing. Include instructions for installing and reproducing your error.

# Feature Requests

### Checklist

- [x] I've read through the [Docs](https://formidable.com/open-source/victory/docs) and [Guides](https://formidable.com/open-source/victory/guides) to make sure this functionality doesn't already exist

- [x] I've searched open issues to make sure I'm not opening a duplicate issue

### Description

Please describe the feature you're requesting in detail.

**Comment by jakubgrzelak** [comment] 2019-04-02 06:11
Hey! I am trying to center the next inside Victory Pie. The code looks like that. 
`          <View style={styles.pieContainer}>
            <Svg>
              <VictoryPie
                width={250}
                height={250}
                padAngle={zerosCount === 2 ? 0 : 3}
                innerRadius={85}
                data={graphData}
                colorScale={['#01C063', '#4B4190', '#02695C']}
                labels={() => null}
              />
                <VictoryLabel
                  textAnchor="middle"
                  verticalAnchor="middle"
                  style={[{ fontSize: 35, color: '#28323B', fontWeight: '600', lineHeight: 40 }, { fontWeight: '600', fontSize: 16 }]}
                  x={SCREEN_WIDTH * 0.5} y={SCREEN_WIDTH * 0.3}
                  // it is hard to make it on the middle on react native so for smaller numbers
                  // like one digit ( three spaces before number ) two digits ( two spaces before)
                  // three digits ( one before) ... this trick makes label always in the middle
                  // you can use it when wiring up
                  text={[this.state.totalCO2Credits, this.state.unit + ' of credit']}
                />
            </Svg>
          </View>`

**Comment by jakubgrzelak** [comment] 2019-04-02 06:15
Unfortunately output looks like that 
![Simulator Screen Shot - iPhone XS Max - 2019-04-02 at 08 03 55](https://user-images.githubusercontent.com/32885164/55379986-14a1b580-551f-11e9-9465-f8aa6f2acd78.png)
The first line looks ok but I cannot center the second line on the screen. This is the biggest problem. It is not an issue related to missing `viewBox` on `svg`. I checked it already. Please have a look at this problem because I am straggling with it days ... Thanks in advance

**Comment by boygirl** [comment] 2019-04-02 18:14
@jakubgrzelak thanks for the reproduction. I'll take a look and see if something is wrong with the `textAnchor` styling in `VictoryLabel`. As a temporary solution you can try adding your text as two separate `VictoryLabel` components

**Comment by boygirl** [comment] 2019-04-28 19:06
@jakubgrzelak I'm going to close this issue, as I can't reproduce it. Here's a sandbox with my solution: https://codesandbox.io/s/pyx14yr277

**Closed by boygirl** 2019-04-28 19:06 UTC
